src/libraries/DAQ/JEventSource_EVIOpp.cc

This fix was tested on the sim-recon code just before (during?) the sim-rexit.  It seemed to have fixed the issue. The change is just reordering 2 lines of code so I reimplement it here.

Likely fix for the bug where 40 event blocks are occassionaly dropped.

---

src/libraries/DAQ/DEVIOWorkerThread.cc
src/libraries/DAQ/DEVIOWorkerThread.h
src/libraries/DAQ/JEventSource_EVIOpp.cc
src/libraries/DAQ/JEventSource_EVIOpp.h

This acknowledges the new SSP bank type (presumably for the DIRC) and prints a few warnings, but then allows the parser to continue so that RunPeriod-2018-08 data can be processed.
Parsing of the bank will be filled in later.

Detect SSP (DIRC) bank data so we don't error on it. 

---

src/libraries/TRACKING/DTrackTimeBased_factory.cc

In the cases where we are trying to add additional hypotheses for a track in the time-based stage, and the fit does not converge or flips sign, discard this track.
This means that we aren't assured that there will be a full set of hypotheses for each track,
but these appear to be garbage, in any case.
This eliminates a problem in which tracks were getting multiple fits to the same hypothesis, which caused strange problems for the comboing in the  analysis library.  This might be a sign of some underlying tracking problem, though...

Reject bad time-based additional hypotheses

---

src/libraries/HDDM/DEventSourceREST.cc
src/libraries/HDDM/DEventSourceREST.h

If multiple tracks with the same hypothesis from one candidate are present in a REST file, pick the one with the best chi^2 by default.  This happened in the latest reconstruction due to some tracking bugs
Required to avoid confusion in the analysis library.

Prune redundant tracks from REST files

---

src/plugins/Utilities/scanf250/JEventProcessor_scanf250.cc
src/plugins/Utilities/scanf250/JEventProcessor_scanf250.h
src/plugins/Utilities/scanf250/SConscript

The output filename is hardcoded to tree_scanf250.root (because the plugin uses the analysis library's tree interface, because I believe the usual root tree interface either can't be used or can't be used multithreaded, since some changes that Paul M made about a year ago).
This version requires that the rocid is between 11 and 22.
To get the events processed in order, use PEVIO:NTHREADS=1 and PNTHREADS=1.
If you run this on short mode data which doesn't contain any Df250WindowRawData, it will run silently and produce an empty output file.

minimal plugin to put Df250WindowRawData into a root tree

---

src/libraries/TRIGGER/DTrigger_factory.cc
src/libraries/TRIGGER/DTrigger_factory.h

(e.g. the main physics trigger).
This is not turned on by default! 
Use with care!

Add option to flag BCAL/FCAL LED trigger events which slip into other  triggers

---

src/libraries/TOF/DTOFHit_factory.cc

TDC times without ADC info are useless!
this caused nan in the walk correction which was alleviated by an amplitude cut but the real issue
is that a TDC hit without ADC info to do a proper walk correction does not deliver a good timing value!

do not use unmatched TDC hits to make DTOFHit:

---

src/libraries/TRIGGER/DTrigger_factory.cc

The problem was introduced in PR #34 - apparently I committed the wrong version of the code?
The line where the main trigger bits was accidentally removed.  So honestly, I'm not sure how anything worked during testing...

Fix reduction in rho yield

---

src/plugins/Utilities/pi0fcalskim/JEventProcessor_pi0fcalskim.cc

Remove rejection of showers near the beam pipe via radial cut.  It was probably there for historical reasons.  Colin has confirmed it is no longer needed.

Update to FCAL pi0 skim.

---

src/plugins/Calibration/HLDetectorTiming/JEventProcessor_HLDetectorTiming.cc
src/plugins/Calibration/HLDetectorTiming/JEventProcessor_HLDetectorTiming.h

Add flag to allow use of normal RF time determination and to skip calibrations with charged tracks.
This will do for initial PrimEx commissioning, probably we should use an FCAL-only RF time determination for these calibrations.

Changes to support PrimEx calibrations & monitoring

---

src/libraries/PID/DEventRFBunch_factory.cc
src/libraries/PID/DEventRFBunch_factory_CalorimeterOnly.cc
src/libraries/PID/DEventRFBunch_factory_CalorimeterOnly.h
src/libraries/PID/DEventRFBunch_factory_FCAL_CCAL.cc
src/libraries/PID/DEventRFBunch_factory_FCAL_CCAL.h
src/libraries/PID/PID_init.cc
src/plugins/Calibration/HLDetectorTiming/JEventProcessor_HLDetectorTiming.cc

Added class for calculating the RF bunch for an event using only calorimeter information, using tag "CalorimeterOnly".  The detectors being used for this calculation can be toggled.  
Also added the ability to use the output of a particular factory as the default RF time calculation via command-line option, e.g., -PEVENTRFBUNCH:USE_TAG=CalorimeterOnly
Combo-based RF bunch calculations are still handled in the ANALYSIS library.
Also some changes for PrimEx calibrations.

Add Calorimeter-only RF Bunch calculation

---

src/libraries/CCAL/SConscript

Seems to be a linker problem with new fortran CCAL libs

Fix for problems with CentOS 6 build

---

src/libraries/HDGEOMETRY/DGeometry.cc

I wrote some code to use the DGeometry::GetCDCNwires method and was dismayed when it didn't work due to the method being empty. This fills it in in case any (including me) needs it at some point in the future.

Fill in DGeometry::GetCDCNwires with values read off from HDDS.

---

src/libraries/DAQ/DEVIOWorkerThread.cc
src/libraries/DIRC/DDIRCPmtHit_factory.cc
src/plugins/monitoring/DIRC_online/JEventProcessor_DIRC_online.cc

With new DIRC LED data using BLOCKLEVEL=40 there was a segfault in the EVIO parser.  A commit in this PR https://github.com/JeffersonLab/halld_recon/commit/b138af4851fa09cb2595bc63f63f8df9d477af34 appears to fix the problem, but should be checked by David.

Fix SSP parser for BLOCKLEVEL>1

---

src/libraries/DAQ/DEVIOWorkerThread.cc
src/plugins/Utilities/evio_writer/DEVIOBufferWriter.cc
src/plugins/Utilities/evio_writer/DEVIOBufferWriter.h

-  Add ability to write out DIRC TDC hits to evio_writer. now they will actually be part of skims!
- Change to EVIO parsing so that it works with these events which have 1 block per event.  Doesn't seem to affect multi block data.

DIRC EVIO updates

---

src/plugins/Utilities/trigger_skims/JEventProcessor_trigger_skims.cc

Missing Get(BCALHits) needed to trigger on BCAL_LED events for energy or number of hits.

Addining missing Get(BCALHits) line

---

src/libraries/HDDM/DEventSourceREST.cc
src/libraries/HDDM/DEventSourceREST.h

Reverts JeffersonLab/halld_recon#121 to stop the crashes reported in issue #136 
We did not observe crashes with the nightly build prior to this pull request (2019-02-26). We could also run successfully when we disable this code altogether (REST:PRUNE_DUPLICATE_TRACKS 0).
In the future, the memory leak should be fixed properly.

Revert "Fix memory leak that occurs when a duplicate track is dropped."

---

src/libraries/CCAL/DCCALShower_factory.cc

For some reason these problems show up in other builds, but my not my test one on the gluons.
I do see them when using the nightly build.  Using a different style of lock, so maybe it will make a difference.

Rearrange things to help with threading issues

---

src/plugins/Utilities/trigger_skims/JEventProcessor_trigger_skims.cc

Increasing BCAL LED skim condition to 1200 hits and disabling the energy condition to avoid GTP events leaking into BCAL LED skim files.

Fix BCAL LED trigger conditions

---

src/libraries/HDDM/event.xml

This is due to a request from Eugene to add a field for optional generator-specific data which can be propagated through the analysis chain.

Add optional data field for "user defined" data in HDDM

---

src/libraries/DANA/DApplication.cc

The SQLITE_TO_LOCAL option is used by the online monitoring system to copy the CCDB file from the group disk disk to a local disk so when all processes start up, they don't content for the same nfs lock. This allows the processes to start up faster.
There has been an issue with a file being partially copied but the time stamp being newer than the original. This now checks both the file size and timestamp to decide if the file should be copied whereas previously only the timestamp was checked.

Check file size as well as timestamp when implementing SQLITE_TO_LOCAL.

---

src/plugins/Calibration/BCAL_TDC_Timing/JEventProcessor_BCAL_TDC_Timing.cc
src/plugins/monitoring/BCAL_online/JEventProcessor_BCAL_online.cc

Only compare TDC and ADC where pulse is big enough that time-walk is small.
Cut out LED events which fail to fire the trigger from the calibration and monitoring.

BCAL TDC mods

---

src/plugins/Utilities/evio_writer/DEVIOBufferWriter.cc
src/plugins/Utilities/evio_writer/DEVIOBufferWriter.h
src/plugins/Utilities/trigger_skims/JEventProcessor_trigger_skims.cc

1) use correct CCAL trigger bits (zero-counting error)
2) write out Df250Scaler objects
Note that currently the software does not read in or write out Df250AsyncPedestal
objects.  If Sasha provides the information for these banks, they can be implemented.

Skim changes

---

src/plugins/Calibration/ST_Tresolution/JEventProcessor_ST_Tresolution.cc
src/plugins/Calibration/ST_Tresolution/JEventProcessor_ST_Tresolution.h

This addresses issue #71. It fixes one instance of a problematic pattern that may cause similar crashes in other plugins. See comments in issue #71 for details.

Fix crash in ST matching

---

src/libraries/KINFITTER/DKinFitter.cc
src/libraries/PID/DParticleID.cc
src/libraries/PID/DParticleID.h
src/libraries/PID/DParticleID_PID1.cc
src/libraries/PID/DParticleID_PID1.h

Reformulates vertex constraints for charged particles in the magnetic field to avoid conditions that lead to NaNs in the kinematic fitting matrices, which were quite common for topologies with detached vertices.
Also adds calibrations for E/p for use with PIDFOM.

Pid update jun19

---

src/libraries/KINFITTER/DKinFitter.cc
src/libraries/KINFITTER/DKinFitter.h
src/libraries/TRACKING/DTrackFitterKalmanSIMD.cc
src/libraries/TRACKING/DTrackFitterKalmanSIMD.h

Reverts back to the old vertex constraint equations, only using the alternate form if the first version has numerical problems due to the argument to arcsin going out of range.  Although the second version of the constraint equations  seemed to have the right behaviour for the means of the pulls, the error distributions looked much too narrow for vertex-only fits.

Kin fit update july19

---

src/libraries/PID/DNeutralShower_factory_PreSelect.cc
src/libraries/PID/DNeutralShower_factory_PreSelect.h

Implement the cuts suggested by Mark Dalton's studies:
- reject showers in the FCAL/BCAL transition region by cutting on BCAL z and FCAL R
- reject showers near the beampipe by making a list of crystals and rejecting showers who have a center inside of them

Implement suggested calorimeter fiducial cuts at analysis level

---

src/libraries/ANALYSIS/DAnalysisUtilities.cc
src/libraries/ANALYSIS/DAnalysisUtilities.h
src/libraries/ANALYSIS/DEventWriterROOT.cc

To help with current skim studies and analyses, we probably need to look into this in more detail in the future.
The theta cut is removed since the list of showers that go into this calculation now has some fiducial cuts applied in the pre-select stage.

Add number of unused showers in ROOT tree format

---

src/plugins/Calibration/BCAL_SiPM_saturation/JEventProcessor_BCAL_SiPM_saturation.cc

to supress warnings.
@eltonssmith should have a look at this one before merging.

Comment out uppeak and downpeak variables, apparently not used

---

src/libraries/CCAL/island.F

Suppress warnings by initializing some variables. Warning about these variables being used uninitialized are spurious according to @ilyalarin. But this change will get rid of the compiler warnings.

Supress warnings by initializing some local variables.

---

src/plugins/monitoring/DIRC_online/JEventProcessor_DIRC_online.cc

This one should be reviewed by @jrstevenjlab.

Comment out locLEDRefTime to suppress warning, variable not used.

---

src/plugins/Calibration/FCAL_LED_shifts/JEventProcessor_FCAL_LED_shifts.cc

Warning suppression fix. @sdobbs should look at this one.

Comment out "slot" declaration to avoid unused variable warning.

---

src/plugins/Calibration/FCAL_TimingOffsets/JEventProcessor_FCAL_TimingOffsets.cc

Requested a review from @sdobbs for this one.

Comment out fcalGeom to supress warning about unused variable.

---

src/libraries/DAQ/DParsedEvent.h
src/libraries/TTAB/DTranslationTable.h

Do not allow DEFTAG when finding factories to place low-level and digihit objects into. This fix will allow tagged factories for these types of objects that can be used to filter them for special studies. Prior to this, the EVIO event source and TTAB would instead place the objects directly into the tagged factory which is not what was wanted.

Fix bug in finding factories for event source and TTAB low-level objects

---

src/libraries/DAQ/DEVIOWorkerThread.cc

Supressing warnings about initialized but unused variables. @faustus123 should have look at this one.

Comment out unused variables to supress warnings.

---

src/programs/Utilities/hdskims/hdmk_skims.py

This change only affects the hdmk_skims.py script.
As an aside, it is not clear at all that it is a good idea to distribute a version of mysql-connector with RCDB and especially to have that automatically added to PYTHONPATH in the environment setup scripts. The version shipped with RCDB is incompatible with python36 and moreover, automatically adding it to the environment blocks the system installed one (almost certainly more likely to be compatible). I think I've been bitten by this at least once before. This fix here is ugly and the time it takes to track down this problem and implement such a fix would be better spent elsewhere.

Remove the RCDB mysql-connector from the path so the system one may be used

---

src/libraries/ANALYSIS/DSourceComboer.cc
src/libraries/ANALYSIS/DSourceComboer.h

treat muons like hadrons in E/p, not like electrons
the IsLepton function is not used anywhere else and could be deleted

default E/p cuts for muons

---

src/plugins/monitoring/BCAL_LED/JEventProcessor_BCAL_LED.cc

Change highlevel directory name to avoide a run time issue where the name conicides with other plugins.

Fix highlevel directory name

---

src/programs/Utilities/hdevio_scan/DMapEVIOWords.cc
src/programs/Utilities/hdevio_scan/DMapEVIOWords.h
src/programs/Utilities/hdevio_scan/hdevio_scan.cc

This fills in a histogram hdevio_scan creates, but until now never actually filled. It is the daq_hits_per_event histo which plots hits as a function of rocid (system type).

Fill in daq_hits_per_event histogram.

---

src/libraries/DAQ/DEVIOWorkerThread.cc
src/plugins/monitoring/DIRC_online/DIRC_North_hit.C
src/plugins/monitoring/DIRC_online/DIRC_digihit.C
src/plugins/monitoring/DIRC_online/DIRC_hit.C

This fixes the check on the BOR header word so that it will accept CDAQ data from Spring2019-11. CDAQ differs in how it formats this word in that it puts the number of crates in the EVIO "num" field whereas hdBOR just puts 01 there. This had been fixed for previous run periods where CDAQ was used. For the current run period, 2 more crates were added. The check now ignores the 8 bit "num" field.
Also included in this pull request are adding the e-mail addresses for DIRC experts to the DIRC_online monitoring macro. It probably be a second pull request, but that would be a pain to do now so it was left in this one.

CDAQ + BOR and DIRC emails

---

src/plugins/Utilities/pi0bcalskim/JEventProcessor_pi0bcalskim.cc
src/plugins/Utilities/pi0bcalskim/JEventProcessor_pi0bcalskim.h
src/plugins/Utilities/pi0fcalskim/JEventProcessor_pi0fcalskim.cc
src/plugins/Utilities/pi0fcalskim/JEventProcessor_pi0fcalskim.h

For pi0 skims to be run over simulated data.  The following switches should be used in that case:
-PPI0BCALSKIM:WRITE_EVIO=0 -PPI0BCALSKIM:WRITE_HDDM=1

Add option to write skims to HDDM

---

src/libraries/DAQ/DEVIOWorkerThread.cc
src/libraries/DAQ/HDEVIO.cc
src/libraries/DAQ/JEventSource_EVIOpp.cc

This fixes two issues with parsing CDAQ data using standard tools.
1. The run number is now found in Fall2019 and later data
2. hdevio_scan understands the ff33 tag so skips printing tons of errors.
This also improves some information in error messages when corrupt fADC250 data is encountered.

Davidl cdaq run number

---

src/plugins/Alignment/tools/MakeCDCConstraintsFile.C

Even though Millepede correctly recognizes keywords with few typo errors, no typos must be better.

Fix typos in a script for Millepede alignment

---

src/libraries/CCAL/DCCALShower_factory.h

The previous syntax is incorrect, too many braces.  Bad of gcc4.8.5 to allow it.
I thought that this fix had been already commited, but I guess not??

fix brace bug, only shows up on more recent compilers (e.g. gcc7)

---

src/plugins/Calibration/TOF_calib/JEventProcessor_TOF_calib.cc

this move will hopefully make the plugin less dependent on timing shifts
within the TOF as long as these shifts are not too large (more than 20ns)

change location of timing peaks and cuts around those peaks

---

src/plugins/Calibration/TOF_calib/JEventProcessor_TOF_calib.cc

the readout window
the TOF TDC readout window was shifted by 250ns and shortened by 400ns

addaped the calibration code to the TDC timing shift due to changes in

---

src/programs/Utilities/hdevio_scan/DMapEVIOWords.cc
src/programs/Utilities/hdevio_scan/DMapEVIOWords.h
src/programs/Utilities/hdevio_scan/daq_words_compare_by_crate.C
src/programs/Utilities/hdevio_scan/hdevio_scan.cc

- Add option to set run number on command line.
- Try extracting run number from file if not specified.
- Use large run number to get latest TTAB if other methods fail.
- Add daq_words_compare_by_crate.C script for comparing two runs by crate. 
- Fix normalization of daq_words_per_event profile histogram.

updates to hdevio_scan

---

src/libraries/TRACKING/DTrackFitterStraightTrack.cc

A strong correlation b/w 's' and FDC cathode residuals is removed by fixing this bug,
where 's' is a hit coordinate along the wire direction.

Fix bug in KF-smoothing for forward straight tracks

---

src/libraries/DAQ/DEVIOWorkerThread.cc
src/libraries/TRD/DGEMHit_factory.cc

Fix issue relating to initializing array with non-POD element type. This was an error for the clang compiler.
This replaces a stack declaration of an array of vector containers whose size is given by a variable. The fix allocates from the heap instead of the stack and wraps the pointer in a shared_ptr so that it is properly deleted when it falls out of scope.
This pattern appeared twice in the code.

Fix to allow builds using clang.

---

src/libraries/TRACKING/DTrackFitter.h
src/libraries/TRACKING/DTrackFitterKalmanSIMD.cc
src/libraries/TRACKING/DTrackFitterStraightTrack.cc

I added a member variable in 'pull_t' class to store the left-right information of the wire plane (first commit).
I also added the derivative calculation part that is necessary for the Millepede calibration of the 't0' parameter (second commit).
This pull request does not contain the plugin-update for the Millepede alignment.
(I will push my modifications of the plugins after cleaning up the code.)

Store some tracking info. for Millepede alignment/calibration

---

src/plugins/Calibration/TOF_calib/JEventProcessor_TOF_calib.cc
src/plugins/Calibration/TOF_calib/JEventProcessor_TOF_calib.h

offsets from ccdb and use it propperly in the code.
the problem was 2 folds
a) the offsets from ccdb are additive but were used subtractive in the code
b) the root writing to separate root file crashed the code. This was fixed by explicitly closing the
separate root file after writing to it at the end.

fix bug in plugin to select the propper regions of interest using the

---

src/plugins/monitoring/BEAM_online/BEAM_overview.C

Add an additional graph to the plots that shows the accidental ratios between the side peaks
and the prompt peak for the first 15 peaks to the left and right of the prompt peak.

improve on the online plotter for the beam condition histograms

---

src/plugins/Utilities/SConscript
src/plugins/Utilities/compton_neutral_skim/JEventProcessor_compton_neutral_skim.cc
src/plugins/Utilities/compton_neutral_skim/JEventProcessor_compton_neutral_skim.h
src/plugins/Utilities/compton_neutral_skim/SConscript
src/plugins/Utilities/eta2g_primexd_skim/JEventProcessor_eta2g_primexd_skim.cc
src/plugins/Utilities/eta2g_primexd_skim/JEventProcessor_eta2g_primexd_skim.h
src/plugins/Utilities/eta2g_primexd_skim/SConscript
src/plugins/Utilities/eta6g_primexd_skim/Combination.cc
src/plugins/Utilities/eta6g_primexd_skim/Combination.h
src/plugins/Utilities/eta6g_primexd_skim/JEventProcessor_eta6g_skim.cc
src/plugins/Utilities/eta6g_primexd_skim/JEventProcessor_eta6g_skim.h
src/plugins/Utilities/eta6g_primexd_skim/SConscript
src/plugins/Utilities/etapi0_primexd_skim/Combination.cc
src/plugins/Utilities/etapi0_primexd_skim/Combination.h
src/plugins/Utilities/etapi0_primexd_skim/JEventProcessor_etapi0_skim.cc
src/plugins/Utilities/etapi0_primexd_skim/JEventProcessor_etapi0_skim.h
src/plugins/Utilities/etapi0_primexd_skim/SConscript
src/plugins/Utilities/single_neutral_skim/JEventProcessor_single_neutral_skim.cc
src/plugins/Utilities/single_neutral_skim/JEventProcessor_single_neutral_skim.h
src/plugins/Utilities/single_neutral_skim/SConscript

Add different skimmers for PRIMEXD
1/ eta2g_primexd_skim -> eta Primakoff in FCAL, evio reduced by 4400
2/ eta6g_primexd_skim -> eta ->3pi0 and etaprime ->2pi0 eta, evio reduced by 575
3/ etapi0_primed_skim -> etapi0/etaeta/pi0pi0 skims, evio reduced by 8
4/ compton "neutral" skim, evio reduced by 36
5/ single "neutral" skim, evio reduced by 12

Add PRIMEXD skimmer

---

src/libraries/TRACKING/DTrackTimeBased_factory.cc

These two additional lines explicitly assign the track time for missing hypotheses, instead of using the poorer resolution drift chamber time initially used in the fit.  
Note: I believe this only affects the DIRC reconstruction, where we use this track time to get the extrapolated hit time at the DIRC plane.  This was found from the observation that pion tracks have better timing resolution than kaon tracks in the DIRC, due to the use of this courser time in the extrapolation.  With this fix, the time resolution for pions and kaons in the DIRC is much more symmetric.

explicitly set start time and T0 for missing track hypotheses

---

src/libraries/PID/DVertex_factory.cc
src/libraries/PID/DVertex_factory.h
src/plugins/Utilities/SConscript
src/plugins/Utilities/cdcbcal_skim/JEventProcessor_cdcbcal_skim.cc
src/plugins/Utilities/cdcbcal_skim/JEventProcessor_cdcbcal_skim.h
src/plugins/Utilities/cdcbcal_skim/SConscript

- Add option to force DVertex to be at the target center, actually useful for other measurements, like those with narrow targets
- Add skim to select events with CDC tracks matched to a BCAL hit

Updates for field-off analysis

---

src/libraries/CDC/DCDCHit_factory.cc
src/libraries/CDC/DCDCHit_factory.h
src/libraries/FDC/DFDCHit_factory.cc
src/libraries/FDC/DFDCHit_factory.h
src/libraries/TRACKING/DTrackFitterStraightTrack.cc
src/libraries/TRACKING/DTrackFitterStraightTrack.h

Adds improvements to fitting in CDC and simplifies extrapolations to start counter and BCAL.
Also adds command-line parameters to disable CDC and FDC hits for testing purposes.

Straight track update apr20

---

src/plugins/monitoring/PSPair_online/HistMacro_PSTimingAlignment.C
src/plugins/monitoring/TrackingPulls/JEventProcessor_TrackingPulls.cc

- change PS timing macro to reduce whitespace
- disable Tree writing in TrackingPulls until it can be made threadsafe

monitoring updates 4/6/2020

---

src/plugins/Analysis/mcthrown_tree/DEventProcessor_mcthrown_tree.cc
src/plugins/Analysis/mcthrown_tree/DEventProcessor_mcthrown_tree.h

Add error warning when there is a mismatch between the type of input file and the behavior of the plugin.

Add error warning for mcthrown_tree plugin

---

src/libraries/TAGGER/DTAGMHit_factory_Calib.cc

an associated tdc hit. This can be selected for a particular run
range by assigning negative to /PHOTON_BEAM/microscope/integral_cuts
table in ccdb. The value in ccdb can be overridden by the command
line option -PTAGMHit:CUT_FACTOR=0.

* Introduce run-dependent option to require all TAGM hits to have

---

src/libraries/FCAL/DFCALShower_factory.cc
src/libraries/FCAL/DFCALShower_factory.h

DFCALShower_factory is changed to add the PRIMEXD ring energy dependence correction. This change is only applied if the C=2 and D=E=0 in the old IU/GlueX energy dependence correction table and if there is a new PRIMEXD energy dependence correction table available.

Add PRIMEXD ring energy dependence correction

---

src/libraries/TRACKING/DTrackFitterKalmanSIMD.cc
src/libraries/TRACKING/DTrackFitterStraightTrack.cc

This implements the remainder of the time to distance parameters in /CDC/drift_parameters which were previously read in, but not used.  Similar function forms are used for both long and short sides of the straw.  At present the previously unused parameters are 0.  
There is only one instance in ccdb where these parameters were non-0 for a production run, this was intensity scan 72312, may 8 2020, for which the calibration failed, the histograms were empty, better parameters were added 3 minutes later using another run at the same pressure. 
They were also non-zero for some very early entries, runs 0-3050 and 3050, in 2015.
non-zero value for a3 (first row), run max = 72312 min = 72312 added at 2020-05-08 18:39:11
non-zero value for c1 (second row), run max = 3050 min = 3050 added at …

Nsj cdc time to distance tweak

---

src/libraries/DANA/DApplication.cc

Currently, the DANA library only manages one set of DGeometry objects.  Since this is run-dependent, in principle there can be more, and there is code set up to handle this case.  But currently it's short-circuited on the "assumption we are still doing development with simulated data and a single set of geometry files".  This has not been the case for awhile now.  So we relax this condition.  I haven't noticed anything wrong in some limited testing.
I would hold off on merging this before the reconstruction launch out of an abundance of caution.
This should help with some of the weird problems with hdview2 and any time we encounter multiple run numbers in one program execution.

Allow handling of multiple different DGeometry objects

---

src/libraries/ANALYSIS/DCutActions.cc
src/libraries/ANALYSIS/DCutActions.h
src/libraries/ANALYSIS/DHistogramActions_Reaction.cc
src/libraries/ANALYSIS/DHistogramActions_Reaction.h
src/libraries/ANALYSIS/DReaction.cc
src/libraries/ANALYSIS/DReaction.h
src/libraries/HDGEOMETRY/DGeometry.cc
src/libraries/TAGGER/DTAGHGeometry.cc
src/libraries/TOF/DTOFHit_factory.cc
src/libraries/TRACKING/DTrackFitterKalmanSIMD.cc
src/plugins/Analysis/ReactionFilter/DReaction_factory_ReactionFilter.cc
src/plugins/Analysis/ReactionFilter/DReaction_factory_ReactionFilter.h

A few different partially related changes:
* New histogram and cut actions for particles with displaced vertices
* New OPTIONAL ReactionFilter options to help reduce file size
* Reduce the number of informational lines printed out to the screen by eliminating unncessary geometry printouts & only printing other messages once per run.  (plans are being discussed to reduce the XML error messages)

Various analysis & QOL improvements

---

src/libraries/ANALYSIS/DAnalysisResults_factory.cc
src/plugins/Calibration/BCAL_attenlength_gainratio/JEventProcessor_BCAL_attenlength_gainratio.cc

- prevent a crash in BCAL_attenlength_gainratio which is affecting monitoring jobs.  the cause is pretty obscure, looks like it will take awhile to get to the bottom of this
- suppress warning messages by preventing non-physics events from going into the comboing pipeline.  not quite sure how they were getting through in the first place...

Sdobbs bug fixes 20200630

---

src/libraries/ANALYSIS/DEventWriterROOT.cc
src/libraries/ANALYSIS/DParticleComboCreator.cc
src/libraries/HDDM/DEventSourceREST.cc
src/libraries/HDDM/DEventWriterREST.cc
src/libraries/HDDM/rest.xml
src/libraries/PID/DChargedTrackHypothesis.h
src/libraries/PID/DDetectorMatches.h
src/libraries/PID/DKinematicPools.cc
src/libraries/PID/DParticleID.cc
src/libraries/PID/DParticleID.h
src/libraries/PID/DParticleID_PID1.cc
src/libraries/PID/DParticleID_PID1.h

Various updates to PIDFOM scheme:
1) Add PIDFOM to tree output
2) Change how E/p is handled, using shared pointers and a dEOverPInfo subclass
3) Add dE/dx from TOF for proton ID
4) Add dependence of dE/dx in CDC and FDC on the number of hits used in the calculation

Pid fom updates

---

src/libraries/DANA/DApplication.h
src/libraries/DAQ/HDEVIO.cc
src/libraries/DAQ/HDEVIO.h
src/libraries/DAQ/JEventSource_EVIOpp.cc
src/libraries/DAQ/JEventSource_EVIOpp.h

This allows one to skip a specific number of blocks of physics events at the EVIO source and keep a number after that. This makes it quicker to jump to the middle of the file and start processing events there.
This also fixes an issue where blocks of physics events where the sync flag is set where being marked as "unknown" instead of "physics".

Skip physics event blocks

---

src/libraries/DANA/DApplication.h
src/libraries/DAQ/HDEVIO.cc
src/libraries/DAQ/HDEVIO.h
src/libraries/DAQ/JEventSource_EVIOpp.cc
src/libraries/DAQ/JEventSource_EVIOpp.h
src/plugins/monitoring/PS_flux/JEventProcessor_PS_flux.cc

This extends two histograms in the PS_flux plugin to cover out to 14400 seconds(=4hr) instead of just the first 500 seconds of a run. A 3rd histogram was added to give a slightly different view of the fiducial map. By extending these, they can be used to verify the correctness of the fiducial map for the entire run.
Please note that this change only includes 1 file. This pull request is being made from a branch copied from a branch which has a pending PR. If you look at this before that is merged, you will see many other changes.

Extend beam fiducial histograms to cover up to 4 hour run

---

src/libraries/DAQ/DBeamCurrent_factory.cc
src/libraries/DAQ/DBeamCurrent_factory.h
src/libraries/DAQ/JEventSource_EVIOpp.cc
src/plugins/Utilities/syncskim/ConversionParms.h
src/plugins/Utilities/syncskim/JEventProcessor_syncskim.cc
src/plugins/Utilities/syncskim/JEventProcessor_syncskim.h
src/plugins/Utilities/syncskim/get_parms2.C

This updates the DBeamPhoton factory to use the rocBCAL4 timestamp instead of the EB calculated avg. timestamp.
It also fixes the syncskim plugin to properly use this everywhere. The conversion values calculated at the end of the job are also now written to a dedicated tree so we don't need to rely on capturing the stdout of the plugin.
This also fixes a problem in syncskim that it was not locking the ROOT mutex during fini when writing and closing the syncskim.root file.
Some debug statements accidentally left in from another recent PR were removed as well.

Update beam trip timestamp conversions

---

src/plugins/monitoring/highlevel_online/HistMacro_Trigger.C

These changes were left in the halld_recon installed in the counting house. I assume they are meant to be permanent, hence this pull request. A Tagger expert should probably confirm this.

Changes to HistMacro_Trigger.C by unknown actor left from Mar. 19th and never committed.

---

src/plugins/monitoring/highlevel_online/HistMacro_LEDTrigger.C

Changed the labels of monitoring plot LED_triggers for distinguishing BCAL upstream and downstream LED front panel triggers.

Changed the labels of the plot for distinguishing BCAL LEDs

---

src/libraries/PID/DParticleID.cc
src/libraries/PID/DParticleID.h

This adds command line switches which are by default on:
PID:CDC_CORRECT_DEDX_THETA
PID:CDC_TRUNCATE_DEDX
There was a bit of faffing over the error handling.  It needs CCDB live or sqlite more recent than July 28 in order to load in the dE/dx correction grid.  If that isn't found, it exits, unless the correction was switched off in the cmd line in which case it doesn't look for the file.

Nsj add pid cmdline args

---

src/plugins/Calibration/TAGM_TW/tw.py

Small changes to make TAGM timewalk calibration script not crash if there are channels with no data in them (like there are in the current run)

TAGM calibration updates

---

src/plugins/monitoring/highlevel_online/HistMacro_Trigger.C

This sometimes created a white box in the L1 Trigger monitoring plot. It is fixed now.

The histograms for BCal LED trigger monitoring were not entirely removed.

---

src/libraries/FCAL/DFCALGeometry.cc
src/libraries/HDGEOMETRY/DGeometry.cc
src/libraries/HDGEOMETRY/DGeometry.h

WARNING:  THIS PR REQUIRES JANA 0.8.2
* Use the new function JGeometry::SetVerbose() to get rid of a lot of annoying (and uneeded) error messages
* Refactored some new geometry requests
This isn't a perfect solution, but I think that it makes sense to push error handling into the client code.  We should review the functions which call these functions to make sure that they handle error conditions properly.  Also, it improves the user experience and reduces the rate of misidentified bugs.
Also, in the future please only put calls to JGeometry::Get() inside the DGeometry object - it helps both in separating out the geometry logic and makes changes like this easier.

Suppress geometry-related warning messages

---

src/plugins/Calibration/PSC_TW/JEventProcessor_PSC_TW.cc
src/plugins/Utilities/ps_skim/JEventProcessor_ps_skim.cc

- Write all events with PS trigger to the PS skim
- Makes sure that DRFTime_factory::init() and brun() are called in the PSC time walk plugin

Primex recon

---

src/programs/Utilities/mergeTrees/mergeTrees.C

Increase size of arrays from 100 to 999, as more than 100 combos per event are possible with multiple photons in the final state. This fixes the crash in issue #464 .
Also fixed error in secondary tree reader for neutral hypo ID.

Increase size of arrays and fixed copy/paste error.

---

src/plugins/Calibration/TAGH_timewalk/scripts/gaussian_fits.C
src/plugins/Calibration/TAGH_timewalk/scripts/offsets/offsets.C
src/plugins/Calibration/TAGH_timewalk/scripts/timewalk_fits.C

- move to double Gaussian fit with separate means
- allow fits with bad chi^2 to accomodate problem channels
- stop pegging all the offsets to the first channel, as is done with other TAGH calibration procedures currently

A few temporary TAGH fixes from the 2020 runs

---

src/libraries/DAQ/Df125TriggerTime.h

The member in Df125TriggerTime was masking a member of the same name in the base class DDAQAddress that actually holds the value. (See GitHub issue #484)

Remove itrigger from Df125TriggerTime 

---

src/libraries/TRIGGER/DTrigger_factory.cc

dL1FrontPanelTriggerBits are always initialized to zero on non
physics trigger events. [rtj]

* make sure that DTrigger object data members dL1TriggerBits and

---

src/plugins/monitoring/BCAL_LED/JEventProcessor_BCAL_LED.cc

comment out unused variables in BCAL_LED plugin

---

src/libraries/TRACKING/DTrackFitterKalmanSIMD.cc

This branch fixes a flaw exposed by the introduction of the Reverse Kalman filter that only impacts electrons and positrons, and only after the first iteration of the reverse filter.   Valgrind did not generate these uninitialized variable errors for the previous version of the code (before the introduction of the reverse filter)  -- this fix does not impact the fitted track results, and does not appear to have any significant impact on track matching to the outer detectors, because the code falls back to the old extrapolation technique if the reverse filter fails.

Fix uninitialised variable bug flagged by valgrind

---

src/libraries/DAQ/DEVIOWorkerThread.cc

This corrects the readout for the itrigger and time objects.  They are not used by the reconstruction code, except in a few of my own (unshared) plugins, but they are extremely useful for diagnostics.

Fix to readout code for Df125TriggerTime

---

src/libraries/ANALYSIS/DSourceComboer.cc
src/plugins/Analysis/ReactionFilter/DReaction_factory_ReactionFilter.cc

- only print reaction lines once, not for every thread
- modified default selection of kaons based on dE/dx, this results in about 3% more entries in the KpKm tree and 5% more for KpLambda

Analysis library tuning

---

src/libraries/PID/DChargedTrackHypothesis_factory.cc

Adds new ccdb tables CDC/dedx_theta/dedx_amp_scale and CDC/dedx_theta/dedx_int_scale to hold scaling factors to be applied to the space charge correction tables to compensate for change in overall gain eg following reintroduction of hit truncation. 
Fixes recent bug in space charge correction in DChargedTrackHypothesis.

Nsj scale dedx correction

---

src/libraries/ANALYSIS/DSourceComboP4Handler.cc
src/libraries/ANALYSIS/DSourceComboVertexer.cc
src/libraries/FCAL/DFCALGeometry.cc

This PR prevents the crash reported in Issue #522 . It was verified that some events from a signal MC sample successfully pass the selection. Since the reaction is extremely rare, we have to use a full run period to evaluate the selection with real data.

Charged AntiSigma Analysis

---

src/plugins/monitoring/RF_online/HistMacro_RF_p1.C

this will create four pictures of the RF self timing peak from FDC, TOF, TAGH and PSC TDC data to be monitored using HYDRA.

modify HistMacro_RF_p1.C to generate RF selftiming pictures for HYDRA AI

---

src/plugins/Utilities/evio_writer/DEventWriterEVIO.cc
src/plugins/Utilities/evio_writer/DEventWriterEVIO.h

Added an option EVIOOUT:CLOSE_FILES which closes all files held open by evio_writer when the input source changes.  This could reasonably be a default, but it's only lightly tested, so I'm keeping this just as an option for now.  Note that if multiple input files have the same name, the corresponding output files get clobbered for now.
This should solve the issue reported by @rjones30 where the number of output threads continually grew when running over a large number of small input files, and eventually use a lot of CPU time.

update to evio_writer to help with jobs running over multiple input files

---

src/libraries/HDDM/DEventSourceREST.cc
src/libraries/HDDM/DEventSourceREST.h
src/libraries/PID/DBeamPhoton_factory.cc
src/libraries/PID/DBeamPhoton_factory_MCGEN.cc
src/libraries/PID/DBeamPhoton_factory_TRUTH.cc
src/libraries/TAGGER/DTAGHGeometry.cc
src/libraries/TAGGER/DTAGHGeometry.h
src/libraries/TAGGER/DTAGMGeometry.cc
src/libraries/TAGGER/DTAGMGeometry.h

This fun piece of code sets the energy of DBeamPhoton objects loaded from a REST file based on the counter number, so you can use the latest tagger energy calibration in your analysis.
There are two main cases to consider:
1. If the REST file contains the counter number for each hit, then the selected CCDB context is used to set the beam photon energy, and the saved energy is ignored.  This works in cases where the counter is properly stored, like in recently generated simulations.  (If your simulations don't have the counter info, they are too old and should be regenerated anyway).
2. If the REST file doesn't contain counter number information, then a reverse lookup is performed to figure out the counter number from the stored photon energy, then the latest energy calibration is applied. …

Set REST beam photon energy based on tagger counter

---

src/plugins/monitoring/RF_online/HistMacro_RF_p1.C

I did introduce a bug when doing a Rebining of the X axis of the self timing plots for the RF signals
did not realize that the method Rebin() is part of the TH1 class not the TAxis class.

fix error for using Rebin in TAxis class rather than histogram class

---

src/plugins/monitoring/fa125_itrig/HistMacro_fa125_itrig.C
src/plugins/monitoring/fa125_itrig/JEventProcessor_fa125_itrig.cc

A bunch of minor changes, mostly for RSAI and in the macro.
Changes to the plugin:
Added a number of events histogram, for RSAI.
Removed rootlocks from the init function as they are not needed there.
Removed the least sig bit from the trigger times before comparing them, as these often differ by 1 between the L and R halves of the crate (I think the clock signal does not reach them at exactly the same time).  Look for any 2 or more bits different in the remainder of the trigger time words, and flag an error if that happens when there are also 2 or more bits wrong in itrigger.

Nsj plugin mod

---

src/libraries/TRIGGER/DTrigger_factory.cc
src/libraries/TRIGGER/DTrigger_factory.h

Enable this by command line option instead.
Sidesteps a bunch of errors coming from the L1 trigger emulation class

Make trigger energy sum emulation optional

---

src/plugins/Analysis/src-ct/1p1pi1pi0/DEventProcessor_1p1pi1pi0.cc
src/plugins/Analysis/src-ct/1p1pi1pi0/DEventProcessor_1p1pi1pi0.h
src/plugins/Analysis/src-ct/1p2pi/DEventProcessor_1p2pi.cc
src/plugins/Analysis/src-ct/1p2pi/DEventProcessor_1p2pi.h

Quoting @sdobbs for reference:
- in multi-threaded JANA, you get one factory object per thread, but there's only ever one plugin object, that means in this case only one DKinFitter object, with multiple threads trying to access it per evnt() function call
- short-term solution here: put the fitting in a lock
- better: put the fitting, etc. into a factory local to the plugin (see p2pi_hists)

Aaust src plugin fix plus sdobbs

---

src/libraries/FCAL/DFCALShower_factory.cc
src/libraries/FCAL/DFCALShower_factory.h

Enable an option to use the primex fcal "log" position with which primex fcal pi0 is calibrated.
By default: SHOWER_POSITION_LOG is false
So to enable this option in the jana cfg: FCAL:SHOWER_POSITION_LOG 1 (-> corrected)
If enable, the primex fcal "log" position will then be used by the "photon" factory, ReactionFilter, & be in REST

Add PrimEx shower position

---

src/libraries/PID/DBeamPhoton_factory_TRUTH.cc

This screws up the mcthrown_tree output when running on the smeared output - running on REST files is fine.

Remove incorrect logic in TRUTH photon construction

---

src/plugins/Calibration/HLDetectorTiming/JEventProcessor_HLDetectorTiming.cc
src/plugins/Calibration/HLDetectorTiming/JEventProcessor_HLDetectorTiming.h

needed for the CPP experiment
enabled by setting HLDETECTORTIMING:NO_START_COUNTER=1

changes to optionally allow timing calibrations without the start counter

---

src/libraries/ANALYSIS/DEventWriterROOT.cc
src/libraries/FCAL/DFCALShower_factory.cc
src/libraries/PID/DNeutralShower.h
src/libraries/PID/DNeutralShower_factory.cc
src/libraries/PID/DNeutralShower_factory.h

Add into the NeutralShower_factor the SC & TOF vetos in order to remove charge hits which are not corresponding to reconstructed tracks

Add blind-spot veto

---

src/plugins/Calibration/PS_timing/JEventProcessor_PS_timing.cc
src/plugins/Calibration/TAGH_timewalk/JEventProcessor_TAGH_timewalk.cc
src/plugins/Calibration/TAGH_timewalk/scripts/time_shift/README_TIME_SHIFT
src/plugins/Calibration/TAGH_timewalk/scripts/time_shift/publish_time_shift.sh
src/plugins/Calibration/TAGH_timewalk/scripts/time_shift/run_time_shift.sh
src/plugins/Calibration/TAGH_timewalk/scripts/time_shift/slice_tagh.C

Use the ADC time to find the closest RF time in PS_timing (fix bug in 
the PS_timing) 
Added PSC reference time to calibrate TAGH  ADC and TDC times 
for channels  with wrongly assigned RF (in TAGH_timewalk).  By default the
RF is assigned by TAGH ADC. A histogram is added, with the reference time 
(RF) defined by the PSC. Add calibration script  `run_time_shift.sh` to correct 
TAGH channels with wrong time (fadc_time_offsets and tdc_time_offsets)

PS and TAGH timing calibration

---

src/libraries/HDDM/DEventSourceREST.cc
src/libraries/PID/DParticleID.cc

Utilize dE/dx information stored for individual planes to set average dE/dx value in memory (despite it not being written to REST files).  Downstream analysis like monitoring histograms and ReactionFilter will then have the relevant information and it can be used in analysis of produced ROOT trees with the DSelector.

Fix TOF dE/dx being read from REST files (needed for RunPeriod-2019-11 recon ver01 files)

---

src/plugins/Calibration/BCAL_TDC_Timing/JEventProcessor_BCAL_TDC_Timing.cc
src/plugins/Calibration/BCAL_attenlength_gainratio/JEventProcessor_BCAL_attenlength_gainratio.cc

To prevent warnings about string lengths.

To prevent warnings about string lengths.

---

src/plugins/Analysis/ReactionFilter/DReaction_factory_ReactionFilter.cc

Otherwise explicitly include initial state. This will leave the naming scheme for most GlueX channels with liquid hydrogen target unchanged, while differentiating between different nuclear targets.

only ignore recoil proton in reaction filter naming scheme for proton target

---

src/libraries/FMWPC/DFMWPCHit.h
src/libraries/FMWPC/DFMWPCHit_factory.cc
src/libraries/FMWPC/DFMWPCTruthHit.h
src/libraries/HDDM/DEventSourceHDDM.cc
src/libraries/HDDM/event.xml
src/plugins/Analysis/fcal_charged/JEventProcessor_fcal_charged.cc
src/plugins/monitoring/cppFMWPC/JEventProcessor_cppFMWPC.cc
src/plugins/monitoring/cppFMWPC/JEventProcessor_cppFMWPC.h
src/plugins/monitoring/cppFMWPC_ana/JEventProcessor_cppFMWPC_ana.cc
src/plugins/monitoring/cppFMWPC_ana/JEventProcessor_cppFMWPC_ana.h

Update FMWPC hit classes to remove dE in favor of q.  Also add amplitude to DFMWPCHit and d (doca to wire) to DFMWPCTruthHit.

Fmwpc hit update

---

src/plugins/Calibration/BCAL_attenlength_gainratio/JEventProcessor_BCAL_attenlength_gainratio.cc

Raw gain ratio plots: 
increase y-axis range by 20% to include some big outliers for recently failed SiPMs; 
decrease total number of bins on most histograms by factor 8 to save resources.

Small mods to BCAL calib plugin

---

src/programs/Utilities/hdskims/hdskims.cc

The old default was tuned to GlueX production running which caused it to quit early for cosmic runs or anything with a smaller event size. This was only noticed by HOSS having inconsistent numbers for the last event from a file and the first event from the next file for some long cosmic runs.

Increase default maximum number of evio events processed by hdskims

---

src/libraries/PID/DNeutralShower_factory.cc

Fixed TOF veto in Neutral Shower factory to take the nearest single shower for both dx and dy, rather than separate components.
Previously would take smallest delta_x and delta_y separately, not necessarily from the same hit.

Fixes to TOF veto in DNeutralShower_factory.cc

---

src/libraries/HDGEOMETRY/DGeometry.cc

only print warning about empty target once per run number

---

src/libraries/FMWPC/DFMWPCHit.h
src/libraries/FMWPC/DFMWPCHit_factory.cc

Turned on various calibration constants and checks, in analogy to the CDC. The FMWPCHit factory now requires FMWPC calibration constants in CCDB, which were introduced today.

Aaust fmwpc hit calib

---

src/programs/Analysis/hdview2/MyProcessor.cc
src/programs/Analysis/hdview2/MyProcessor.h
src/programs/Analysis/hdview2/fmwpc_mainframe.cc
src/programs/Analysis/hdview2/hdv_mainframe.cc
src/programs/Analysis/hdview2/hdv_mainframe.h
src/programs/Analysis/hdview2/hdview2.cc
src/programs/Analysis/hdview2/hdview2.h

This implements a new feature to allow hdview2 to automatically skip events not containing some desired objects. IT is terribly fast, but much faster than clicking through manually.
This also includes some visualization of the CTOF for CPP/NPP

hdview2 Skip events and CTOF

---

src/libraries/DAQ/Df125EmulatorAlgorithm_v2.cc

Bring back the BOR config values that haven't been used here since a Halloween bug ate them several years ago.  The emulator has been using the defaults instead of the real config values (if it was ever used).
Also removed the warning messages that are mostly false.

Nsj restore fa125 emulation

---

src/plugins/Utilities/cdc_emu/JEventProcessor_cdc_emu.cc
src/plugins/Utilities/cdc_emu/JEventProcessor_cdc_emu.h
src/plugins/Utilities/cdc_scan/JEventProcessor_cdc_scan.cc
src/plugins/Utilities/cdc_scan/JEventProcessor_cdc_scan.h

CDC_scan plugin makes root trees from the fa125 low level data, pulse time, amplitude, etc.
In this PR it was modified to include the FDC data by default, and the option was added 
(-PEVIO:F125_EMULATION_MODE=2 -PCDC_SCAN:EMU=1) to make branches 
containing emulated data, using the emulation functions in the DAQ library.
CDC_emu plugin generates similar output but has its own inc file containing the emulation code and reads in the fa125 config parameters from the roccdc1 etc cnf files. This is less user friendly than the other plugin but does not need BORconfig data.
In this PR it was modified only slightly, to make the name of the configuration files that it reads in more generic.

Nsj extend cdc scan plugin to include emulated data

---

src/libraries/HDDM/DEventSourceREST.cc
src/programs/Utilities/hddm/hddm-c.cpp

These fixes are inspired by the compiler warnings in the monthly build email. No actual behavior changes are entailed, just code cleanup. -rtj

Fix string buffer overflow rtj

---

src/libraries/DAQ/DEVIOWorkerThread.cc
src/libraries/DAQ/DEVIOWorkerThread.h
src/libraries/DAQ/JEventSource_EVIOpp.cc
src/libraries/DAQ/JEventSource_EVIOpp.h

Avoids a problem which appeared during the runs 121153-121157. Binary dump only with verbosity > 7.

New command line option to skip wrongly formated F250 signals.

---

src/libraries/TRACKING/DTrackTimeBased_factory.cc

Fixes bug that causes a crash when the run number changes.

clear cdc_rmid vector before doing all the push_backs

---

src/libraries/ANALYSIS/DAnalysisUtilities.cc
src/libraries/ANALYSIS/DAnalysisUtilities.h
src/plugins/Analysis/ReactionEfficiency/DCustomAction_MissingMatch.cc
src/plugins/Analysis/ReactionEfficiency/DCustomAction_MissingMatch.h
src/plugins/Analysis/ReactionEfficiency/DEventProcessor_ReactionEfficiency.cc
src/plugins/Analysis/ReactionEfficiency/DEventWriterROOT_ReactionEfficiency.cc
src/plugins/Analysis/ReactionEfficiency/DEventWriterROOT_ReactionEfficiency.h
src/plugins/Analysis/ReactionEfficiency/DEventWriterROOT_factory_ReactionEfficiency.h
src/plugins/Analysis/ReactionEfficiency/DFactoryGenerator_ReactionEfficiency.h
src/plugins/Analysis/ReactionEfficiency/DReaction_factory_ReactionEfficiency.cc
src/plugins/Analysis/ReactionEfficiency/DReaction_factory_ReactionEfficiency.h

Add reactions to ReactionEfficiency for missing pi0 studies, missing proton against 4 charged pions, etc.  Also include distance from trajectory of missing track projection to TOF and BCAL as additional possible filtering on "found" tracks.

Reaction efficiency enhancements

---

src/libraries/HDDM/DEventSourceREST.cc
src/libraries/HDDM/DEventSourceREST.h
src/libraries/HDDM/DEventWriterREST.cc
src/libraries/HDDM/rest.xml
src/libraries/PID/DChargedTrackHypothesis.h
src/libraries/PID/DChargedTrackHypothesis_factory.cc
src/libraries/PID/DDetectorMatches.h
src/libraries/PID/DDetectorMatches_factory.cc
src/libraries/PID/DDetectorMatches_factory.h
src/libraries/PID/DParticleID.cc
src/libraries/PID/DParticleID.h

Add DDetector matching object for CTOF points to reconstruction and to REST output.   Right now there is a +-20 cm matching cut in both x and y, configurable by command-line parameters.

Add ctof matching

---

src/libraries/CCAL/DCCALShower.h
src/libraries/CCAL/DCCALShower_factory.cc

Add hits used in a cluster explicitly to the shower object instead of using the AddAssociatedObject mechanism, which was causing a memory leak.

Fixes memory leak in DCCALShower factory

---

src/libraries/HDGEOMETRY/DGeometry.cc
src/libraries/TRIGGER/DL1MCTrigger_factory.cc
src/libraries/TRIGGER/DL1MCTrigger_factory.h
src/libraries/TRIGGER/DTrigger_factory.cc

Reduce some of the output when the job is starting up to reduce confusion (or at least try to).
Also, reenable a feature for looking at trigger energy sums in data since this seems to be working better now.

Reduce error messages on startup

---

src/plugins/Calibration/TOF_calib/JEventProcessor_TOF_calib.cc

that the pedestal determination was ok.
This pull request is a small change in the TOF_calib plugin that skimms the tof data using digi hits for
calibration further up. The code has been changed to discard any TOF hit where the QF for the pedestal
determination is set. this means the pedestal determination failed and a "constant" value is subtracted
which comes from CCDB. This value may not be the best. So the prudent course of action is to not use
these hits.

change code to use only TOF hits with good QF to make sure

---

src/libraries/ANALYSIS/DEventWriterROOT.cc
src/libraries/ANALYSIS/DHistogramActions_Independent.cc
src/libraries/ANALYSIS/DHistogramActions_Independent.h
src/plugins/Analysis/ReactionFilter/DReaction_factory_ReactionFilter.cc

This PR includes a few useful tools for studying trigger energy sums for different final states
* the FCAL and BCAL energy sums are now written out as part of the standard PART ROOT trees
* the ReactionFilter plugin now makes trigger energy sum histograms for each reaction, and only for combos which pass some cut on the kinematic fit quality (currently CL > 5%)
Note that the code that runs the energy sum estimation for raw data was only fixed recently, so we would need to use these tools on either MC samples or with a new monitoring launch.

Some more updates related to trigger studies

---

src/libraries/ANALYSIS/DSourceComboP4Handler.cc
src/libraries/include/particleType.h
src/plugins/Analysis/ReactionFilter/DReaction_factory_ReactionFilter.cc

- default decay: Sigma_c++ -> Lambda_c pi+
- mass range 2.2 - 2.7 GeV
- also adapted some of the other mass ranges

Added Sigma_c++ to the analysis library

---

src/libraries/HDDM/DEventSourceREST.cc

Properly set TAGH energy based on current geometry

---

src/libraries/FMWPC/DCPPEpEm_factory.cc
src/libraries/FMWPC/DCPPEpEm_factory.h
src/libraries/FMWPC/DFMWPCCluster.h
src/libraries/FMWPC/DFMWPCCluster_factory.cc
src/libraries/HDDM/DEventSourceREST.cc
src/libraries/HDDM/DEventWriterREST.cc
src/libraries/HDDM/DEventWriterREST.h
src/libraries/HDDM/rest.xml
src/libraries/PID/DChargedTrackHypothesis.h
src/libraries/PID/DChargedTrackHypothesis_factory.cc
src/libraries/PID/DDetectorMatches.h
src/libraries/PID/DDetectorMatches_factory.cc
src/libraries/PID/DDetectorMatches_factory.h
src/libraries/PID/DParticleID.cc
src/libraries/PID/DParticleID.h

Added matching for FMWPC clusters to track projections to REST output and optionally some additional FCAL-related quantities.  To enable writing the latter, set -PPID:ADD_FCAL_DATA_FOR_CPP=1.   Changed DCPPEpEm code to get parameters needed for mu/pi separation directly from the track matching data for each track.  To fully test this, one needs to enable TensorFlowLite.

Add fmwpc matches

---

src/libraries/CCAL/DCCALShower_factory.cc

That should guard against the crash described in issue #789 . It does not change the underlying algorithm.

prevent a crash in DCCALShower_factory, removed debug printout

---

src/plugins/monitoring/TAGM_online/HistMacro_TAGMCOL.C
src/plugins/monitoring/TAGM_online/JEventProcessor_TAGM_online.cc

microscope column 9, 27, 81 and 99 and add a root macro to plot these histograms to be also used in online monitoring and HYDRA
this will serve as a monitoring tool to check that the focal plane of the electrons in the tagger hodoscope is where is should be. During the last run period 2023-01 we moved the center to counter 4 from the bottom. (total of 6 segments)

add four histograms plotting the intensity distribution over the tagger

---

src/libraries/CDC/DCDCHit_factory_Calib.cc
src/libraries/CDC/DCDCHit_factory_Calib.h

also move the variable CDC_HIT_THRESHOLD from being a global variable definition in the .cc file to be a public member the the class in the .h file. This makes the code hopfefull more complient with standards and more thread safe.
The is needed to make sure the use of the variable CDC_HIT_THRESHOLD is threadsafe

move all include directives from the .cc code to the .h incude file and

---

src/plugins/Utilities/evio_writer/DEventWriterEVIO.cc
src/plugins/monitoring/FDC_Efficiency/JEventProcessor_FDC_Efficiency.cc
src/plugins/monitoring/FMWPC_Performance/JEventProcessor_FMWPC_Performance.cc

Few root lock/unlock mismatches, which could potentially cause problems with multithreading. Thanks to @nsjarvis for discovering these.

Aaust root locks 2024

---

src/libraries/CCAL/CCAL_init.cc
src/libraries/CCAL/DCCALGeometry.cc
src/libraries/CCAL/DCCALGeometry_factory.h
src/libraries/CCAL/DCCALHit.h
src/libraries/CCAL/DCCALHit_factory.cc
src/libraries/CCAL/DCCALHit_factory.h
src/libraries/CCAL/DCCALRefDigiHit.h
src/libraries/CCAL/DCCALShower.cc
src/libraries/CCAL/DCCALShower.h
src/libraries/CCAL/DCCALShower_factory.cc
src/libraries/CCAL/DCCALShower_factory.h
src/libraries/CCAL/DCCALTruthShower.h
src/libraries/CCAL/DCCALTruthShower_factory.cc
src/libraries/CCAL/DCCALTruthShower_factory.h
src/libraries/CCAL/ccal.h

The first and third commits are purely aesthetic changes to make all the code in the CCAL library use consistent tab characters for alignment. There were also some small changes (primarily in DCCALShower_factory.cc) to remove unnecessary and ugly white spaces). I also removed some non-useful comments and corrected the description of the 'address' used in the island clusterization code. 
The second commit is the only functional change to the code. It corrects an issue in the CCAL shower factory where in rare cases an element beyond the range of a vector was attempting to be accessed (e.g. the 10th element of a vector with only 5 elements was trying to be accessed).

CCAL Style Changes & Memory Issue Fix

---

src/libraries/BCAL/DBCALHit_factory.cc

Was accidentally only loading half of it

Fix loading of BCAL bad channel table

---

src/libraries/BCAL/DBCALHit_factory.cc
src/plugins/monitoring/BCAL_online/bcal_hit_occupancy.C

The other occupancy plots use digihits.  We need to monitor the
calibrated hits to check the BCAL bad channel map

Add BCAL occupancy plot for calibrated hits

---

src/libraries/TAGGER/DTAGHHit_factory_Calib.cc
src/libraries/TAGGER/DTAGMHit_factory_Calib.cc

If these aren't applied, then when we try to label these as bad quality channels, we just get a bunch of TDC-only hits, which we want to avoid.

Add channel quality cuts to tagger TDC channels

---

src/libraries/ANALYSIS/DEventWriterROOT.cc

This is important for FSRoot analyses, the current flattening for thrown trees do not currently work without this option

Add option to only write out final state particles to thrown trees

---

src/libraries/ANALYSIS/DAnalysisResults_factory.cc

Finally understood what was going on. The offset was not reset for each reaction. This fixes #837 both for data and MC.

reset trigger studies histogram offset for next reaction

---

src/plugins/monitoring/CDC_dedx/JEventProcessor_CDC_dedx.cc
src/plugins/monitoring/CDC_dedx/JEventProcessor_CDC_dedx.h

I'm not sure if there is a neater way of coding this.  
Is it possible to query DTrackTimeBased to find out if it used the mass hypothesis with the best FOM? 
I assumed not and made a separate loop through the charged tracks to get to the best FOM track that way.

Add dedx vs p histos with best FOM (the existing histos show all hypos)

---

src/libraries/DAQ/JEventSource_EVIO.cc
src/libraries/DAQ/JEventSource_EVIO.h
src/libraries/DAQ/JEventSource_EVIOpp.cc
src/libraries/DAQ/JEventSource_EVIOpp.h
src/libraries/EVENTSTORE/DEventSourceEventStore.cc
src/libraries/EVENTSTORE/DEventSourceEventStore.h
src/libraries/HDDM/DEventSourceHDDM.cc
src/libraries/HDDM/DEventSourceHDDM.h
src/libraries/HDDM/DEventSourceREST.cc
src/libraries/HDDM/DEventSourceREST.h
src/plugins/Utilities/eviodana/DEventSourceEVIO.cc
src/plugins/Utilities/eviodana/DEventSourceEVIO.h

**Description:**
This PR addresses the crash occurring at the end of REST file processing in JANA2 event sources, as detailed in issue #834. The root cause was the outdated exception handling mechanism inherited from JANA1, where reaching the end of a file would throw an exception to indicate that all events had been processed. In case of JANA1, it was getting perceived as a signal of no more events if exception thrown was RETURN_STATUS::kNO_MORE_EVENTS but no more in JANA2 that's why it was not crashing with JANA1 but now in JANA2 it is. Ideally also it's not good to throw any kind of exception just to end things. That's why  JANA2 introduced an `Emit` function that returns Result enums properly indicating end instead of throwing exception approach.
**Key Changes:**
- Replaced the …

Fix EOF Crash in JANA2 Event Sources (#834)

---

src/libraries/HDDM/DEventSourceHDDM.cc
src/libraries/HDDM/DEventSourceHDDM.h
src/libraries/HDDM/DEventSourceREST.cc
src/libraries/HDDM/DEventSourceREST.h
src/libraries/TAGGER/DTAGHHit_factory_Calib.cc
src/libraries/TAGGER/DTAGHHit_factory_Calib.h
src/libraries/TAGGER/DTAGMHit_factory_Calib.cc
src/libraries/TAGGER/DTAGMHit_factory_Calib.h

This is mainly for random hits that are merged in, when the bad channel mask was updated after the random trigger files were created
Addresses issue #810

Add code to mask dead channels when reading in HDDM/REST events

---

src/libraries/FCAL/DFCALGeometry.cc
src/libraries/FCAL/DFCALHit_factory.cc
src/libraries/TRIGGER/DL1MCTrigger_factory_DATA.cc

Change how the FCAL-2 geometry is loaded to handle indexing of the FCAL channels taking into account the hole in the center for the ECAL but still maintaining the meaning of the order of the 2800 entries on the ccdb calibration tables.

Fcal2 index fix

---

src/libraries/FMWPC/DFMWPCHit_factory.cc
src/libraries/FMWPC/DFMWPCHit_factory.h
src/libraries/HDDM/DEventSourceHDDM.cc
src/libraries/HDDM/DEventWriterHDDM.cc
src/libraries/HDDM/event.xml

* add handling of writing out all the appropriate fields for FMWPC hits to HDDM event format
* add ability to apply thresholds to both the digit hit amplitude and integral. we can implement the appropriate CCDB table after this

updates for CPP low level hits

---

src/libraries/FCAL/DFCALCluster_factory.cc

The internal id previously set in jana1 is no longer present in jana2, so this revision fixes a bug that was exposed when we switched from jana1 to jana2.

Explicitly set id value in local userhit_t structure.

---

src/programs/Analysis/hd_dump/MyProcessor.cc

In `hd_dump`, inside `MyProcessor::BeginRun` (JANA2) or `MyProcessor::brun` (JANA1), a vector `factory_names` is used to check user inputs. This list is expected to contain all available factories, including tagged ones.
In JANA1, this was handled using `GetFactoryNames`, which returned a list of strings where tagged factories were explicitly labeled with `fac_name:tag`:
```cpp
vector<string> factory_names;
eventLoop->GetFactoryNames(factory_names);
```
Example output:
```
{"DTAGHTDCDigiHit", "DTAGMHit", "DTAGMHit:Calib", "DTAGHHit", "DTAGHHit:Calib", "DTAGMHit:TRUTH", "DTAGHHit:TRUTH"}
```
In JANA2, there is no direct equivalent function. Instead, factory objects are retrieved using:
```cpp
event->GetFactorySet()->GetAllFactories()
```
which returns a list of `JFactory*` pointers instead …

Fix Incorrect Handling of Tagged Factories in JANA2 Porting (hd_dump)

---

src/libraries/ANALYSIS/DParticleComboCreator.cc
src/libraries/ANALYSIS/DParticleComboCreator.h
src/libraries/PID/DBeamPhoton_factory.cc
src/libraries/PID/DBeamPhoton_factory.h

The memory leak was caused by the `NOT_OBJECT_OWNER` flag being set in `DBeamPhoton_factory::Init()`. This flag informs JANA that the factory does not own its objects, preventing JANA from automatically deleting them.
```cpp
void DBeamPhoton_factory::Init()
{
// Parameter initialization code
SetFactoryFlag(NOT_OBJECT_OWNER);
}
```
Deletion was managed inside `evnt` (JANA1) and `Process` (JANA2) as follows:
**JANA1 (`evnt` method):**
```cpp
jerror_t DBeamPhoton_factory::evnt(jana::JEventLoop *locEventLoop, uint64_t locEventNumber)
{
dResourcePool_BeamPhotons->Recycle(dCreated);
dCreated.clear();
_data.clear();
// Other factory code inserting objects into _data
dCreated = _data;
return NOERROR;
}
```
**JANA2 (`Process` method):**
```cpp
void DBeamPhoton_factory::Process(const …
```

Fix Memory Leak Due to `NOT_OBJECT_OWNER` Flag in `DBeamPhoton_factory`

---

src/libraries/CCAL/DCCALGeometry_factory.h
src/libraries/CCAL/DCCALHit_factory.cc
src/libraries/CCAL/DCCALHit_factory.h
src/libraries/CCAL/DCCALShower_factory.cc
src/libraries/DIRC/DDIRCPmtHit_factory.cc
src/libraries/ECAL/DECALHit_factory.cc
src/libraries/ECAL/DECALHit_factory.h
src/libraries/FMWPC/DCTOFHit_factory.cc
src/libraries/FMWPC/DCTOFHit_factory.h
src/libraries/FMWPC/DCTOFPoint_factory.cc
src/libraries/FMWPC/DFMWPCCluster_factory.cc
src/libraries/FMWPC/DFMWPCHit_factory.cc
src/libraries/FMWPC/DFMWPCHit_factory.h
src/libraries/TRD/DTRDHit_factory_Calib.cc
src/libraries/TRD/DTRDHit_factory_Calib.h

Addresses issue #814 
I tried running over a few different run periods, and they seemed to work.  I did get an occasional crash for 2022-05, but this seemed to have to do with some unrelated geometry issue?  Might be good to get an independent check on this.

Add CCDB tables to control which detectors are used in different run periods

---

src/libraries/DAQ/JEventSource_EVIOpp.cc
src/libraries/DAQ/JEventSource_EVIOpp.h

The issue arose due to a difference in how **JANA1** and **JANA2** handle multiple event sources. In **JANA1**, an event source for the next file was only created once the previous file had been read and its associated event source had been closed. However, in **JANA2**, all event sources are instantiated at the start to set parameters during the initialization phase. This means that if **76 input files** are provided, **76 event sources** are created upfront.
The **EVIOpp event source** creates additional threads (4 default threads per event source) within its constructor. In **JANA2**, since all event sources for the input files are instantiated during the initialization phase, creating **76 event sources** for **76 input files** resulted in the launch of **4 x 76 threads**, in addition …

Fix #911 - Program crashing with multiple evio input files

---

src/libraries/DAQ/DEVIOWorkerThread.cc
src/libraries/DAQ/DEVIOWorkerThread.h
src/libraries/DAQ/JEventSource_EVIOpp.cc
src/libraries/DAQ/JEventSource_EVIOpp.h

Added command line option to skip SSP format error, similar to other modules as discussed in issue https://github.com/JeffersonLab/halld_recon/issues/920

add option to skip DIRC SSP parsing error

---

src/libraries/DAQ/DEVIOWorkerThread.cc
src/libraries/DAQ/DEVIOWorkerThread.h
src/libraries/DAQ/JEventSource_EVIOpp.cc
src/libraries/DAQ/JEventSource_EVIOpp.h

- throw JExceptionDataFormat exception in case of data decoding error
- add in EVIO:PARSE_HELICITY switch for skipping helicity info
Addresses #924

Fix error handling in helicity board decoding

---

src/libraries/DAQ/DEVIOWorkerThread.cc
src/libraries/DAQ/DEVIOWorkerThread.h

data
Get rid of all these anoying warnings about Truncated FDC data
limit the output to 10

limit warning messages for missing data words from truncated FDC/CDC

---

src/libraries/HDDM/DEventSourceREST.cc

This PR fixes a crash in `DEventSourceREST` caused by manually creating a `JCalibrationGeneratorCCDB` instance without setting its required `JApplication` context. When this context is missing, `JCalibrationGeneratorCCDB::MakeJCalibration` fails while attempting to access the `ccdb:cache` parameter, which determines whether CCDB caching should be enabled.
When using the standard JANA interface to retrieve a `JCalibration` object, the `JCalibrationManager::acquire_services` method automatically configures the associated `JCalibrationGeneratorCCDB`, including setting the `JApplication` pointer. This pointer is later required to retrieve parameters such as `ccdb:cache`.
However, in `DEventSourceREST`, the generator was being created manually without setting this application context, …

Fix crash in DEventSourceREST by setting JApplication on CCDB generator

---

src/libraries/FCAL/DFCALCluster_factory.cc
src/plugins/Analysis/monitoring_hists/HistMacro_Matching_ECAL.C
src/plugins/Utilities/evio_writer/DEVIOBufferWriter.cc

Initial updates to enable EVIO skimming for the ongoing run.  This affects cases where we want to write out only specific objects, not the whole event, e.g. pi0 skims.
Basically, the problem was that extracting the low-level hits from high-level objects took advantage of the JANA behavior of Get(), which was changed in JANA2.  Now we have to go through the object inheritance chain to get at them.
This PR doesn't cover all possible output objects, but I think it does cover the ones that are currently used.  I did some light tests
One additional change I had to make is how hit IDs are calculated in the FCAL clusterizer.  I don't think this should affect anything, but we probably want to run some more comprehensive checks on this to be sure.

updates to EVIO skimming for JANA2

---

src/plugins/Analysis/p2pi_hists/DCustomAction_p2pi_hists.cc
src/plugins/Analysis/p2pi_hists/DCustomAction_p2pi_hists.h
src/plugins/Analysis/p2pi_hists/HistMacro_CircMonitor.C

p2pi plugin now creates 4 additional histograms for forming circular polarisation asymmetry.

add circular polarisation monitoring to p2pi plugin

---

src/programs/Utilities/mkplugin/mkplugin

Bug removed:
- SetTypeName moved from destructor to constructor in mkplugin generated JEventProcessor code
Improvements:
- [Improvements by Alex - mentioned here]

 Improve mkplugin script & fix a bug

---

src/plugins/monitoring/RF_online/JEventProcessor_RF_online.cc

Temporary fix suggested by David Lawrence.
Longer-term solution is to refactor the functions called in this factory to a stand-alone utility class.

Fix to RF_online

---

src/plugins/Alignment/MilleFieldOff/JEventProcessor_MilleFieldOff.cc
src/plugins/Alignment/MilleFieldOff/JEventProcessor_MilleFieldOff.h
src/plugins/Alignment/MilleFieldOn/JEventProcessor_MilleFieldOn.cc
src/plugins/Alignment/MilleFieldOn/JEventProcessor_MilleFieldOn.h

This PR fixes the function signatures for `::Process` and `::BeginRun` in both `JEventProcessor_MilleFieldOn` and `JEventProcessor_MilleFieldOff` classes to ensure they **correctly override** the corresponding virtual methods from `JANA::JEventProcessor`.
Previously, these methods were incorrectly declared, causing them to be treated as **new member functions** rather than overrides. As a result, they were **never invoked during the event processing lifecycle**, leading to the `hd_root.mil` file not being generated as expected.
With this fix:
* The overridden methods are now correctly registered and executed by JANA.
* The event lifecycle behavior is restored.
* Output file `hd_root.mil` is now properly filled.

Fix Methods Signatures in MilleField Plugins (Fixes #1007)

---

src/dana_rest.hddm
src/libraries/DAQ/JEventSourceGenerator_EVIOpp.cc
src/libraries/DAQ/JEventSource_EVIOpp.cc
src/libraries/DAQ/JEventSource_EVIOpp.h

1. Fix issue #961: When JANA2 shuts down early due to errors parsing parameters, JEventSource_EVIOpp::Open() does not get called, but the destructor to JEventSource_EVIOpp does. The destructor (correctly) does not assume that JEventSource_EVIOpp::Open() was called, and checks whether the pointers it is trying to delete are nullptr or not. However, these checks fail, because these pointers were never initialized and hence contain random garbage. Initializing the pointers allows the destructor to succeed and not segfault. This also fixes a related bug where the JEventSource_EVIOpp destructor segfaults due to an exception during processing, which would otherwise print the exception details and cleanly exit.
2. Move the parameter registration logic from JEventSource_EVIOpp::Open() to …

Improvements to JEventSource_EVIOpp

---

src/libraries/HDDM/DEventSourceREST.cc
src/libraries/HDDM/DEventWriterREST.cc
src/libraries/HDDM/rest.xml
src/libraries/PID/DChargedTrackHypothesis.h
src/libraries/PID/DChargedTrackHypothesis_factory.cc
src/libraries/PID/DDetectorMatches.h
src/libraries/PID/DDetectorMatches_factory.cc
src/libraries/PID/DDetectorMatches_factory.h
src/libraries/PID/DParticleID.cc
src/libraries/PID/DParticleID.h
src/libraries/TRACKING/DTrackTimeBased_factory.cc
src/libraries/TRACKING/DTrackTimeBased_factory.h
src/plugins/Analysis/monitoring_hists/HistMacro_Matching_ECAL.C

Improves track matching to ECAL showers and adds track matching to single isolated hits in the ECAL.  Adds matching information to REST output.  Add ECAL times to list of sources of t0 for time-based tracking.

Ecal track matching update

---

src/libraries/BCAL/DBCALGeometry_factory.h

**Description:**
Fixes [halld\_sim#363](https://github.com/JeffersonLab/halld_sim/issues/363) that mentions`mcsmear` crashing with JANA 2.4.2 due to a factory cycle.
* Set `SetRegenerateFlag(true)` in `DBCALGeometry_factory`, ensuring geometry objects are generated via `Process()` instead of triggering recursive calls through `GetObjects()`.
* Verified that `mcsmear` runs without crashing under JANA 2.4.2.

Fix mcsmear crash with JANA 2.4.2

---

src/libraries/DAQ/DEVIOWorkerThread.cc

This PR updates the exception handling logic in `DEVIOWorkerThread::Run` to use JANA2-compliant methods for exiting the application with a specific exit code.
Previously, the code used:
```cpp
japp->Quit(10); // or -1
```
However, in JANA2 (`JApplication::Quit(bool skip_join)`) above syntax does not set the exit code instead it sets `skip_join=true`, and the application exits with default code 0.
This PR replaces those lines with:
```cpp
japp->SetExitCode(10);  // or -1
japp->Quit(true);
```
This ensures the application exits with the correct non-zero code when encountering malformed or bad data, enabling better behavior in scripts and production workflows that rely on proper exit codes.
Fixes #1031.

Update DEVIOWorkerThread::Run to use JANA2-compliant quitting syntax

---

src/plugins/monitoring/highlevel_online/HistMacro_Trigger.C

This removes a long-standing memory leak in rootspy and RSAI.

Do not create new histograms if they already exist.

---

src/libraries/TRACKING/DTrackFitterKalmanSIMD.cc
src/libraries/TRD/DTRDPoint_factory.cc
src/libraries/TRD/DTRDPoint_factory.h
src/libraries/TRD/DTRDSegment_factory.cc
src/libraries/TRD/DTRDSegment_factory.h

Gate more geometry calls by checking to see if the detector is installed or not
this reduces spurious error messages
Addresses #1044

Update handling of GEM-TRD geometry

---

src/plugins/monitoring/highlevel_online/AmorphousNormalization/amo.py
src/plugins/monitoring/highlevel_online/HistMacro_Beam.C
src/plugins/monitoring/highlevel_online/JEventProcessor_highlevel_online.cc
src/plugins/monitoring/highlevel_online/JEventProcessor_highlevel_online.h

* highlevel_online plugin writes out a histogram with normalization values from an amorphous run, that was previously saved in CCDB
* HistMacro_Beam uses this histogram to normalize the beam energy spectrum
* `./amo.py MINRUN MAXRUN` is used to fill the database with values from amorphous runs with this run range
It is indicated in the canvas that the values come from CCDB:

Use CCDB for amorphous normalization of photon beam energy monitoring

---

src/programs/Analysis/hd_root/hd_root.cc

This PR introduces a new parameter, **`PLUGIN_CHECK`**, which is **true by default**. It controls whether the program checks for a plugins value. When enabled, hd_root exits with `-1` if no plugins are set, alerting users who may have forgotten to specify any plugins. Users who intentionally want to run without plugins—for testing or other purposes—can disable this check by passing `-PPLUGIN_CHECK=0` on the command line.
**Enhances:** #1041
The decision to add this parameter, rather than just issuing a warning without exiting, was based on discussions in #1049.
This change balances safety (alerting users to missing plugins) with flexibility (allowing intentional bypass of the check).

Introduce PLUGIN_CHECK to allow skipping plugin check

---

src/libraries/FMWPC/DCPPEpEm_factory.cc
src/libraries/FMWPC/DCPPEpEm_factory.h
src/plugins/Utilities/SConscript
src/plugins/Utilities/epem_ml_skim/JEventProcessor_epem_ml_skim.cc
src/plugins/Utilities/epem_ml_skim/JEventProcessor_epem_ml_skim.h

Updated epem_ml_skim plugin for JANA2 and gave it the ability to produce a pion skim file for the purpose of pion subtraction. Updated DCPPEpEm_factory, which epem_ml_skim depends on, to be able to use other targets other than lead.

epem_ml_skim plugin update
