JeffersonLab/halld_recon

src/plugins/monitoring/FCAL_invmass/JEventProcessor_FCAL_invmass.cc
src/plugins/monitoring/FCAL_invmass/JEventProcessor_FCAL_invmass.h
src/plugins/monitoring/FCAL_invmass/fcal_invmass.C

Modified the invariant mass monitoring plugin to include three histograms of different quality restrictions to verify the MLP is functioning.

Mlp monitoring

---

src/libraries/DAQ/DAQ_init.cc
src/libraries/DAQ/DDIRCADCHit.h
src/libraries/DAQ/DDIRCTDCHit.h
src/libraries/DAQ/DDIRCTriggerTime.h
src/libraries/DAQ/DEVIOWorkerThread.cc
src/libraries/DAQ/DParsedEvent.h

Only tested with run 50127 which has no hits, but does have headers and trigger times.

Implement parsing of DRIC data. 

---

src/SBMS/sbms_setenv.py

Restores changes from David's commit 6356cd4 that got lost in the split.

Add AMPPLOTTER and SQLITECPP_HOME. Cleanup some inconsisted indentation.

---

src/libraries/CCAL/CCAL_init.cc
src/libraries/CCAL/DCCALDigiHit.h
src/libraries/TTAB/DTranslationTable.cc
src/libraries/TTAB/DTranslationTable.h

Add CompCal to the translation table and add CCAL DigiHit table

Ccal recon

---

src/plugins/Analysis/ccal_hits/DEventProcessor_ccal_hits.cc
src/plugins/Analysis/ccal_hits/DEventProcessor_ccal_hits.h
src/plugins/Analysis/ccal_hits/SConscript

Reconstruction of CCAL hits

---

src/plugins/Analysis/SConscript
src/plugins/Analysis/ccal_display/DEventProcessor_ccal_display.cc
src/plugins/Analysis/ccal_display/DEventProcessor_ccal_display.h
src/plugins/Analysis/ccal_display/RootHeader.h
src/plugins/Analysis/ccal_display/SConscript

CCAL display

---

src/libraries/CCAL/CCAL_init.cc
src/libraries/CCAL/DCCALRefDigiHit.h
src/libraries/TTAB/DTranslationTable.cc
src/libraries/TTAB/DTranslationTable.h
src/libraries/include/GlueX.h

Add CCAL Reference PMTs (subdetector CCAL_REF)

Add CCAL Reference PMTs

---

src/plugins/Analysis/SConscript
src/plugins/Analysis/fcal_led/DEventProcessor_fcal_led.cc
src/plugins/Analysis/fcal_led/DEventProcessor_fcal_led.h
src/plugins/Analysis/fcal_led/SConscript

FCAL gain calibration using LED

FCAL gain calibration using LED

---

src/libraries/CCAL/DCCALGeometry.h
src/libraries/TTAB/DTranslationTable.cc
src/plugins/Analysis/ccal_display/DEventProcessor_ccal_display.cc
src/plugins/Analysis/ccal_hits/DEventProcessor_ccal_hits.cc
src/plugins/Analysis/ccal_hits/DEventProcessor_ccal_hits.h

Modify index ranges for CCAL rows and columns. Update plugins

Modify index ranges for CCAL rows and columns. Update plugins

---

src/libraries/CCAL/CCAL_init.cc
src/libraries/CCAL/DCCALCluster.cc
src/libraries/CCAL/DCCALCluster.h
src/libraries/CCAL/DCCALCluster_factory.cc
src/libraries/CCAL/DCCALCluster_factory.h
src/libraries/CCAL/DCCALGeometry.cc
src/libraries/CCAL/DCCALGeometry.h
src/libraries/CCAL/DCCALHit.h
src/libraries/CCAL/DCCALHit_factory.cc
src/libraries/CCAL/DCCALHit_factory.h

Add CCAL Hit factory and templates for CCAL Clusters

Add CCAL Hit factory and templates for CCAL Clusters

---

src/plugins/Calibration/FCAL_LED_shifts/JEventProcessor_FCAL_LED_shifts.cc
src/plugins/Calibration/FCAL_LED_shifts/JEventProcessor_FCAL_LED_shifts.h
src/plugins/Calibration/FCAL_LED_shifts/SConscript
src/plugins/Calibration/SConscript

Initial version of this plugin.

First version of new plugin for calibrating 4 ns FCAL fADC shfits

---

src/plugins/monitoring/lowlevel_online/HistMacro_CCAL_lowlevel.C
src/plugins/monitoring/lowlevel_online/JEventProcessor_lowlevel_online.cc
src/plugins/monitoring/lowlevel_online/JEventProcessor_lowlevel_online.h
src/plugins/monitoring/occupancy_online/CCAL_occupancy.C
src/plugins/monitoring/occupancy_online/JEventProcessor_occupancy_online.cc
src/plugins/monitoring/occupancy_online/JEventProcessor_occupancy_online.h

Added some histos for low-level monitoring of the compton calorimeter

Ccal monitoring

---

src/libraries/CCAL/DCCALCluster.h
src/libraries/HDGEOMETRY/DGeometry.cc
src/libraries/HDGEOMETRY/DGeometry.h
src/plugins/monitoring/occupancy_online/CCAL_occupancy.C
src/programs/Analysis/hdview2/MyProcessor.cc
src/programs/Analysis/hdview2/hdv_mainframe.cc
src/programs/Analysis/hdview2/hdv_mainframe.h
src/programs/Analysis/hdview2/hdv_optionsframe.cc

Modifications to hdview2 to draw CCAL.
Also minor fix to CCAL occupancy macro for RootSpy

Hdview2 primex

---

src/plugins/Calibration/HLDetectorTiming/JEventProcessor_HLDetectorTiming.cc

This version should be used for online monitoring now.

Remove some debug code that was accidentally left in

---

src/plugins/Calibration/FCAL_LED_shifts/JEventProcessor_FCAL_LED_shifts.cc
src/plugins/Calibration/FCAL_LED_shifts/JEventProcessor_FCAL_LED_shifts.h

Mostly forgot to change the histogram ranges.  This mode is rarely needed.

Fixes for FCAL 4 ns calibrations with beam data

---

src/programs/Analysis/hdview2/trk_mainframe.cc
src/programs/Utilities/hd_geom_query/hd_geom_query.cc

* fix old hdds geometry utility, had fallen behind in maintenance [rtj]

* fix an occasional segfault in trk_mainframe.cc  [rtj]

---

src/libraries/PID/DParticleID.cc
src/libraries/PID/DParticleID.h

Changes to use new z-dependent SC resolution parameterization

Use new start counter resolution parameterization

---

src/plugins/Calibration/HLDetectorTiming/JEventProcessor_HLDetectorTiming.cc
src/plugins/Calibration/HLDetectorTiming/JEventProcessor_HLDetectorTiming.h

Will need to actually test/develop more with some data

More changes for CCAL and DIRC timing calibrations

---

src/libraries/CCAL/DCCALShower_factory.cc
src/libraries/CCAL/DCCALShower_factory.h
src/libraries/CCAL/adcgam_bk.inc
src/libraries/CCAL/hycal.h
src/libraries/CCAL/island.F

- first try at an energy weighted time sum
- add a lock in the shower factory so that we aren't stomping over common blocks
- minor fixes

Changes to CCAL algorithm

---

src/libraries/DIRC/DDIRCGeometry_factory.h
src/libraries/DIRC/DDIRCLut_factory.h
src/libraries/HDGEOMETRY/DGeometry.cc
src/libraries/PID/DParticleID.cc
src/libraries/TAGGER/DTAGHGeometry_factory.h
src/libraries/TAGGER/DTAGMGeometry_factory.h
src/libraries/TOF/DTOFGeometry_factory.h
src/libraries/TRACKING/DTrackFitterKalmanSIMD.h
src/libraries/TRACKING/DTrackTimeBased_factory.cc
src/libraries/TRIGGER/DL1MCTrigger_factory.cc

fixes bug getting start counter timing resolutions from db, and also a bookkeeping bug for time-base tracks.  Fix some issues with uninitialized pointers.

Sc timing resol and various other fixes

---

src/libraries/BCAL/DBCALGeometry_factory.h
src/libraries/CCAL/DCCALGeometry_factory.h
src/libraries/DAQ/Df250EmulatorAlgorithm_factory_v2.h
src/libraries/PAIR_SPECTROMETER/DLumi_factory.h
src/libraries/PAIR_SPECTROMETER/DPSGeometry_factory.h
src/libraries/PID/DParticleID_factory_PID1.h
src/libraries/TTAB/DTranslationTable_factory.h

@faustus123 gets an award for the only one to get this consistently right

fix more unitialized pointers in factories

---

src/plugins/monitoring/DIRC_online/DIRC_digihit.C
src/plugins/monitoring/DIRC_online/DIRC_hit.C
src/plugins/monitoring/DIRC_online/JEventProcessor_DIRC_online.cc
src/plugins/monitoring/occupancy_online/DIRC_occupancy.C
src/plugins/monitoring/occupancy_online/JEventProcessor_occupancy_online.cc
src/plugins/monitoring/occupancy_online/JEventProcessor_occupancy_online.h

Update plugins and macros to display south box only and show more diagnostics for LED and physics triggers.

Dirc commissioning 2019

---

src/libraries/CCAL/DCCALShower_factory.cc
src/libraries/CCAL/DCCALShower_factory.h
src/libraries/CCAL/cphoto.inc
src/libraries/CCAL/hycal.h
src/libraries/CCAL/island.F

I updated the CCAL shower factory to include post-clusterization processing such as adjacent cluster merging and position corrections.

Ccal shower edits

---

src/libraries/PID/DEventRFBunch_factory_Calibrations.cc

Add option to override the source used for the RF used in various cal…ibrations, mainly HLDectectorTiming

Calibration RF override

---

src/plugins/monitoring/ST_online_efficiency/JEventProcessor_ST_online_efficiency.cc

change code to use gPAMRS as it is inteded to

---

src/libraries/DAQ/JEventSource_EVIOpp.cc

This addresses a bug Richard pointed out where EVIO files are kept open until the end of the process, even though all events have already been read. He noticed it when trying to run jobs on the OSG that opened many (~200) files and the files were not being closed until the end of the program.
JANA has a mechanism for dealing with this exact issue, but there was a bug in it that caused list of outstanding events to have an extra entry for the after-the-last event which didn't actually exist. This commit removes that from the list so that the file is closed as soon as all of its events have been processed.

Close EVIO files as they are finished.

---

src/plugins/Utilities/evio_writer/DEVIOBufferWriter.cc

Add fadc250 scaler bank to sync events for crates with no hits (pulse integrals)

Add scalers to crates with no hits (Pulse Integral)

---

src/plugins/Analysis/TPOL_tree/JEventProcessor_TPOL_tree.cc
src/plugins/Analysis/TPOL_tree/JEventProcessor_TPOL_tree.h

Additions to TPOL tree for creation of all future TPOL trees.

TPOL additions

---

src/libraries/DAQ/DAQ_init.cc
src/libraries/DAQ/Df250EmulatorAlgorithm_factory.h
src/libraries/DAQ/Df250EmulatorAlgorithm_factory_v2.h
src/libraries/DAQ/Df250EmulatorAlgorithm_factory_v3.h
src/libraries/DAQ/Df250EmulatorAlgorithm_v2.cc
src/libraries/DAQ/Df250EmulatorAlgorithm_v3.cc
src/libraries/DAQ/Df250EmulatorAlgorithm_v3.h
src/libraries/DAQ/JEventSource_EVIOpp.cc

See above.  Minor changes in algorithm from previous version.  Tests are successful so far.

Add emulation for new fADC250 firmware version

---

src/libraries/TRACKING/DTrackFitterKalmanSIMD.cc

Various changes to try to prevent premature abandonment of tracks

Track fitter update jun19v2

---

src/libraries/TRACKING/DHoughFind.h
src/libraries/TRACKING/DTrackCandidate_factory_FDCCathodes.cc
src/libraries/TRACKING/DTrackCandidate_factory_FDCCathodes.h
src/libraries/TRACKING/DTrackFitterKalmanSIMD.cc

Adds the Hough transform method for finding track candidates in the FDC.

Fdc track finder update jun19v2

---

src/libraries/CCAL/island.F

Round one of warning suppression. Not all warnings are addressed. Changes in this pull request should not affect functionality.

changes to suppress warning, should not affect functionality

---

src/libraries/FCAL/DFCALShower_factory.cc

Added statements to fetch depth correction parameters from the ccdb rather than have them hardcoded in FCAL Shower Factory

New ccdb constants

---

src/libraries/include/particleType.h

Supporting some new developments

Additional definitions needed for event generators

---

src/libraries/PID/DNeutralShower_factory_PreSelect.cc

Bug fix to FCAL fiducial region calculation

Sdobbs fiducial fix

---

src/libraries/ANALYSIS/DAnalysisUtilities.cc

@jrstevenjlab might want to have a look at this.

Comment out unused variable.

---

src/libraries/ANALYSIS/DHistogramActions_Independent.cc
src/libraries/HDGEOMETRY/DGeometry.cc
src/libraries/HDGEOMETRY/DGeometry.h
src/libraries/PID/DParticleID.cc
src/libraries/PID/DParticleID.h
src/libraries/PID/DParticleID_PID1.cc
src/libraries/TOF/DTOFGeometry.cc
src/libraries/TOF/DTOFGeometry.h
src/libraries/TOF/DTOFHit_factory.cc
src/libraries/TOF/DTOFPaddleHit_factory.cc
src/libraries/TOF/DTOFPoint_factory.cc
src/libraries/TTAB/DTTabUtilities_factory.cc
src/plugins/Calibration/TOF_calib/JEventProcessor_TOF_calib.cc
src/plugins/monitoring/TOF_Eff/JEventProcessor_TOF_Eff.cc
src/plugins/monitoring/TOF_online/JEventProcessor_TOF_online.cc
src/plugins/monitoring/occupancy_online/JEventProcessor_occupancy_online.cc

First pass at updates for fall running with upgraded TOF
* Generalize TOF geometry code for TOF v1 and v2
* Increase size of paddle-based histograms for largest TOF size
* New TOF geometry triggers pulling constants from TOF2/ directory

Recon/monitoring updates for TOF upgrade

---

src/plugins/Calibration/HLDetectorTiming/JEventProcessor_HLDetectorTiming.cc

suppress warnings

---

src/plugins/Analysis/imaging/JEventProcessor_imaging.cc

@staylorjlab should look at this one

warning suppression, comment out unused variables

---

src/plugins/monitoring/timing_online/JEventProcessor_HLDetectorTiming.cc

@sdobbs should review this one.

Suppress warnings.

---

src/libraries/CCAL/DCCALShower.h
src/libraries/HDDM/DEventSourceREST.cc
src/libraries/HDDM/DEventSourceREST.h
src/libraries/HDDM/DEventWriterREST.cc
src/libraries/HDDM/DEventWriterREST.h
src/libraries/HDDM/rest.xml

Add CCAL showers to REST format.

CCAL REST update

---

src/SBMS/sbms.py
src/libraries/DAQ/JEventSource_EVIOpp.cc
src/libraries/DAQ/JEventSource_EVIOpp.h
src/libraries/TTAB/DTranslationTable.cc
src/libraries/TTAB/DTranslationTable.h
src/programs/Utilities/SConscript
src/programs/Utilities/hdskims/HDEVIOWriter.cc
src/programs/Utilities/hdskims/HDEVIOWriter.h
src/programs/Utilities/hdskims/SConscript
src/programs/Utilities/hdskims/hdbyte_swapout.cc
src/programs/Utilities/hdskims/hdbyte_swapout.h
src/programs/Utilities/hdskims/hdmk_skims.py
src/programs/Utilities/hdskims/hdskims.cc
src/programs/Utilities/hdskims/skiminfo.sql

This adds the hdskims tool and its helper script. These are used to speed up the skims.
This also adds the EVIO:SYSTEMS_TO_PARSE_FORCE config. parameter to allow users a way to specify how conflicts between the hardcoded and CCDB versions of the rocid map by system.

hdskims + EVIO:SYSTEMS_TO_PARSE_FORCE

---

src/libraries/TAGGER/DTAGHGeometry.cc
src/libraries/TAGGER/DTAGHGeometry.h
src/libraries/TAGGER/DTAGMGeometry.cc
src/libraries/TAGGER/DTAGMGeometry.h

Correct beam photon energy in reconstruction for PrimEx runs

Correct beam photon energy in reconstruction for PrimEx runs

---

src/libraries/TOF/DTOFHit_factory.cc
src/libraries/TOF/DTOFHit_factory.h

needed for data from new running period

Recalculate the number TOF channels on the fly, used for sanity checks

---

src/plugins/monitoring/BCAL_LED/JEventProcessor_BCAL_LED.cc
src/plugins/monitoring/BCAL_LED/JEventProcessor_BCAL_LED.h

Updating BCAL_LED to include two mode pulsing cycle.

BCAL LED two-mode

---

src/plugins/Analysis/F250_mode10_pedestal/JEventProcessor_F250_mode10_pedestal.cc
src/plugins/Analysis/F250_mode10_pedestal/JEventProcessor_F250_mode10_pedestal.h
src/plugins/Analysis/F250_mode10_pedestal/SConscript
src/plugins/Analysis/F250_mode8_pedestal/JEventProcessor_F250_mode8_pedestal.cc
src/plugins/Analysis/F250_mode8_pedestal/JEventProcessor_F250_mode8_pedestal.h
src/plugins/Analysis/F250_mode8_pedestal/SConscript
src/plugins/Analysis/SConscript
src/plugins/monitoring/BCAL_online/JEventProcessor_BCAL_online.cc

Add a version of Mark Dalton's fADC pedestal width plugin with updated name and compatibility with modern jana. Add more timing plugins to BCAL_online plugin

Jz bcal plugins

---

src/plugins/Utilities/SConscript
src/plugins/Utilities/twogamma_fcal_skim/JEventProcessor_twogamma_fcal_skim.cc
src/plugins/Utilities/twogamma_fcal_skim/JEventProcessor_twogamma_fcal_skim.h
src/plugins/Utilities/twogamma_fcal_skim/SConstruct

Two gamma skim, extend mass region to 1GeV

Chandra calib

---

src/libraries/TRACKING/DTrackFitterStraightTrack.cc

Fix straight track extrapolation crash

---

src/libraries/TRACKING/DTrackFitterKalmanSIMD.cc
src/libraries/TRACKING/DTrackFitterKalmanSIMD.h

Adds extrapolations to TRD planes for non-zero B-field.

Add extrapolations to TRD planes

---

src/libraries/ANALYSIS/DSourceComboTimeHandler.cc

especially if you compare the chi2 for RF bunches
fixes issue #257

Bigger is not always better

---

src/plugins/Analysis/Z2pi_trees/scripts/DSelector_Z2pi_trees2.C
src/plugins/Analysis/Z2pi_trees/scripts/DSelector_Z2pi_trees2.h
src/plugins/Analysis/Z2pi_trees/scripts/MakeAmpToolsFlat.C
src/plugins/Analysis/Z2pi_trees/scripts/MakeAmpToolsFlat.h
src/plugins/Analysis/Z2pi_trees/scripts/call_DSelector2.C
src/plugins/Analysis/Z2pi_trees/scripts/plot_Z2pi_trees.C
src/plugins/Analysis/Z2pi_trees/scripts/streamline2.csh

Save scripts for processing get_2pi_primakoff event generator with AmpTools

save latest scripts working with geant4

---

src/plugins/monitoring/SConscript
src/plugins/monitoring/TrackingPulls_straight/JEventProcessor_TrackingPulls_straight.cc
src/plugins/monitoring/TrackingPulls_straight/JEventProcessor_TrackingPulls_straight.h
src/plugins/monitoring/TrackingPulls_straight/SConscript

For Millepede alignment using straight track runs.

Add a plugin 'TrackingPulls_straight'

---

src/plugins/monitoring/occupancy_online/JEventProcessor_occupancy_online.cc

Fixed axis label in rootspy macro.

Fixed axis label in rootspy macro.

---

src/libraries/TOF/DTOFHit_factory.cc
src/libraries/TOF/DTOFHit_factory.h

just to help out with calibration studies in the future

add command line switches to set time windows in TOF

---

src/libraries/TOF/DTOFHit_factory.cc
src/libraries/TOF/DTOFHit_factory.h
src/plugins/Calibration/TAGH_timewalk/JEventProcessor_TAGH_timewalk.cc

Because... why wouldn't you do this... in the first place?  I'm going home...

Use actual TDC time instead of the timewalk corrected time for calibrations

---

src/libraries/DIRC/DDIRCLEDRef_factory.cc
src/libraries/DIRC/DDIRCLEDRef_factory.h

Thanks to Bill for providing the new constants and updates to the factory

Led ref bill

---

src/libraries/TAGGER/DTAGHHit_factory.cc
src/libraries/TAGGER/DTAGMHit_factory.cc

by the cluster algorithm [rtj]

* cross-reference (AddAssociatedObject) tagger hits that are hidden

---

src/libraries/ANALYSIS/DEventWriterROOT.cc
src/libraries/ANALYSIS/DEventWriterROOT.h
src/libraries/ANALYSIS/DHistogramActions_Independent.cc
src/libraries/ANALYSIS/DHistogramActions_Independent.h
src/libraries/ANALYSIS/DHistogramActions_Reaction.cc
src/libraries/ANALYSIS/DHistogramActions_Reaction.h
src/libraries/ANALYSIS/DSourceComboP4Handler.cc
src/libraries/ANALYSIS/DSourceComboTimeHandler.cc
src/libraries/ANALYSIS/DSourceComboer.cc
src/libraries/CCAL/DCCALShower.cc
src/libraries/CCAL/DCCALShower.h
src/libraries/CCAL/DCCALShower_factory.cc
src/libraries/CCAL/DCCALShower_factory.h
src/libraries/PID/DEventRFBunch_factory.cc
src/libraries/PID/DNeutralShower_factory.cc
src/libraries/PID/DNeutralShower_factory.h
src/libraries/PID/DNeutralShower_factory_PreSelect.cc
src/libraries/PID/DNeutralShower_factory_PreSelect.h
src/plugins/Analysis/SConscript
src/plugins/Analysis/compton/JEventProcessor_compton_simple.cc
src/plugins/Analysis/compton/JEventProcessor_compton_simple.h
src/plugins/Analysis/compton/Makefile
src/plugins/Analysis/compton/SConscript

1/ Add CCAL into the neutral shower factory and the corresponding histograms
(covariance error matrix contains dummy values at the moment but will be updated before the end of Feb w/ correct values)
2/ Correct a segmentation fault in DCCALShower_factory.cc 
DCCALShower_factory::d2c
DCCALShower_factory::cell_hyc
by puting the uper limit of the array to 499 instead of 500

Ijaegle primex

---

src/plugins/monitoring/TrackingPulls/JEventProcessor_TrackingPulls.cc
src/plugins/monitoring/TrackingPulls/JEventProcessor_TrackingPulls.h
src/plugins/monitoring/TrackingPulls/PlotCDCStrawResiduals.C
src/plugins/monitoring/TrackingPulls/PlotCathodeResiduals.C
src/plugins/monitoring/TrackingPulls/PlotCathodeResidualsLocal.C
src/plugins/monitoring/TrackingPulls/PlotWireResiduals.C
src/plugins/monitoring/TrackingPulls/PlotWireResidualsLocal.C
src/plugins/monitoring/TrackingPulls/SConscript
src/plugins/monitoring/TrackingPulls_straight/JEventProcessor_TrackingPulls_straight.cc
src/plugins/monitoring/TrackingPulls_straight/JEventProcessor_TrackingPulls_straight.h

Prepare TTree member to store the residual info. for Millepede alignment

Store more residual info. in TrackingPulls,TrackingPulls_straight

---

src/plugins/Calibration/HLDetectorTiming/JEventProcessor_HLDetectorTiming.cc

If the magnetic field is off, look at positively charged tracks, since that is the default for straight tracks.

Fix in HLDT for straight tracks

---

src/plugins/Calibration/FCAL_Pi0HFA/JEventProcessor_FCAL_Pi0HFA.cc

Includes Colin's unmerged changes, with some fixes to accessing objects so that it doesn't crash.

Sdobbs pi0calib fix

---

src/plugins/Alignment/MilleFieldOff/JEventProcessor_MilleFieldOff.cc
src/plugins/Alignment/MilleFieldOff/JEventProcessor_MilleFieldOff.h
src/plugins/Alignment/MilleFieldOff/Mille.cc
src/plugins/Alignment/MilleFieldOff/Mille.h
src/plugins/Alignment/MilleFieldOff/SConscript

Add t0 derivatives
Cleaning up codes

Update MilleFieldOff plugin

---

src/plugins/Alignment/MilleFieldOff/JEventProcessor_MilleFieldOff.cc
src/plugins/Alignment/MilleFieldOff/JEventProcessor_MilleFieldOff.h
src/plugins/Alignment/MilleFieldOn/JEventProcessor_MilleFieldOn.cc
src/plugins/Alignment/tools/pede.py

…gnment
Unnecessary sentences in MilleFieldOff are removed.

Bug fix in MilleFieldOn (& Add a helper script)

---

src/plugins/monitoring/highlevel_online/HistMacro_Trigger.C

attempt to make the monitoring for L1 trigger bits easier to understand for shift crews

---

src/plugins/monitoring/DIRC_online/DIRC_digihit.C
src/plugins/monitoring/DIRC_online/DIRC_hit.C
src/plugins/monitoring/highlevel_online/HistMacro_Beam.C
src/plugins/monitoring/highlevel_online/HistMacro_Trigger.C
src/plugins/monitoring/occupancy_online/DIRC_North_occupancy.C
src/plugins/monitoring/occupancy_online/DIRC_occupancy.C

These are the latest version from the counting house to fix a couple small bugs and add guidance to the DIRC macros.

Rootspy bugs and DIRC guidance

---

src/plugins/monitoring/CDC_online/CDC_occupancy.C

Beni, please could you check the call conditions?  Thanks!

Nsj cdc occupancy guidance

---

src/plugins/Calibration/HLDetectorTiming/HistMacro_OnlineCalorimeter.C
src/plugins/Calibration/HLDetectorTiming/HistMacro_OnlinePID.C
src/plugins/Calibration/HLDetectorTiming/HistMacro_OnlineRF.C
src/plugins/Calibration/HLDetectorTiming/HistMacro_OnlineTPOL.C
src/plugins/Calibration/HLDetectorTiming/HistMacro_OnlineTagger.C
src/plugins/Calibration/HLDetectorTiming/HistMacro_OnlineTracking.C
src/plugins/Calibration/HLDetectorTiming/HistMacro_TaggerRFAlignment.C
src/plugins/Calibration/HLDetectorTiming/HistMacro_TaggerRFAlignment2.C
src/plugins/Calibration/HLDetectorTiming/HistMacro_TrackMatchedTiming.C

Update defaults for current running period.
Also move some plots around, add expert emails, and some guidance for users in RootSpy.
Please don't merge right away - let's give people some time to review the guidance and 
make sure that the email lists are correct.

Timing monitoring updates

---

src/libraries/DAQ/DEVIOWorkerThread.cc

encoding bug characterized by a pulse with zero peak value, followed
by a long sequence of repeated time words. [rtj]

* harden the fadc250 decoding algorithm against a particular kind of

---

src/plugins/Utilities/compton_neutral_skim/JEventProcessor_compton_neutral_skim.cc
src/plugins/Utilities/etapi0_primexd_skim/JEventProcessor_etapi0_skim.cc
src/plugins/Utilities/single_neutral_skim/JEventProcessor_single_neutral_skim.cc

Correct bug found by Drew in the time calculation i.e. use proper unit for TMath::C() m/s -> m/ns

Correct bug in time calc TMath::C() is m/s unit needs to be m/ns

---

src/libraries/DAQ/DEVIOWorkerThread.cc

is encountered, if the data following the bad section is wacky. [rtj]

* escape from the parser loop for FADC250 pulse data after bug#1

---

src/libraries/HDDM/DEventSourceHDDM.cc
src/libraries/HDDM/DEventSourceREST.cc

by the DEventSourceXXXX constructory. [rtj]
* add checks at input that the hddm record container is not empty
each time a new record is pulled from the input stream. [rtj]

* add checks on the type of hddm file when it is opened for input

---

src/libraries/PID/DBeamPhoton_factory.cc
src/plugins/Calibration/TAGH_timewalk/scripts/timewalk_fits.C

A couple small updates related to the TAGH:
* modify the timewalk algorithm to better handle counters with hardware problems
* require TAGH DBeamPhotons to have both an ADC and TDC hit

April 2020 TAGH updates

---

src/libraries/TAGGER/DTAGMHit_factory_Calib.cc

this is supposed to work. [rtj]

* fix the logic of int_cuts[i] < 0, and add commentary on how

---

src/plugins/monitoring/highlevel_online/HistMacro_LEDTrigger.C
src/plugins/monitoring/highlevel_online/JEventProcessor_highlevel_online.cc
src/plugins/monitoring/highlevel_online/JEventProcessor_highlevel_online.h

Modified the Monitoring/highlevel_online plugin by including BCAL LED  pseudoTrigger and code for Triggerplots

Modified the Monitoring/highlevel_online plugin 

---

src/plugins/Calibration/FCAL_Pi0HFA/JEventProcessor_FCAL_Pi0HFA.cc

Add couples of 2D histo to be able to look at the non-linear correction for different rings

Add QC for non-linear correction

---

src/libraries/HDDM/DEventSourceREST.cc
src/libraries/HDDM/DEventSourceREST.h
src/libraries/TRACKING/DTrackFitterKalmanSIMD.cc

Fixes the reconstruction code to put the reported track position in the global coordinate system and accommodates this change when track info is retrieved from REST files.

Track position fix

---

src/plugins/Utilities/pi0fcalskim/JEventProcessor_pi0fcalskim.cc

fixed using wrong parameters in FCAL pi0 skim plugin

---

src/libraries/ANALYSIS/DAnalysisUtilities.cc
src/libraries/ANALYSIS/DAnalysisUtilities.h
src/libraries/ANALYSIS/DEventWriterROOT.cc

Addresses one step in issue https://github.com/JeffersonLab/halld_recon/issues/375

Add unused shower variable summed over only showers which pass quality cut

---

src/libraries/ANALYSIS/DHistogramActions_Reaction.cc

Whoops.  Who needs negative numbers anyway...

Forgot an absolute value call in accidental subtraction

---

src/plugins/Calibration/FCAL_Pi0TOF/JEventProcessor_FCAL_Pi0TOF.cc
src/plugins/Calibration/FCAL_Pi0TOF/JEventProcessor_FCAL_Pi0TOF.h
src/plugins/Utilities/pi0fcaltofskim/JEventProcessor_pi0fcaltofskim.cc

I added the trigger bit and BeamPhoton in the primex fcal pi0 skimmer and update the primex calibrator to be able to do the pi0 calibration with the updated log position.

Update primex pi0 skimmer and calibrator

---

src/libraries/CCAL/DCCALShower_factory.cc
src/libraries/TRIGGER/DL1MCTrigger_factory.cc
src/libraries/TRIGGER/DL1MCTrigger_factory.h

Should especially help out simulations

Clean up more console output

---

src/libraries/PID/DNeutralShower_factory_PreSelect.cc
src/libraries/PID/DNeutralShower_factory_PreSelect.h

* Add option to cut on the shower quality by default (will make non-zero when the relevant studies are completed)
* Avoid annoying (and unneeded) warning message

Changes to shower preselect cuts

---

src/plugins/monitoring/BCAL_Hadronic_Eff/ROOT_macros/README
src/plugins/monitoring/BCAL_Hadronic_Eff/ROOT_macros/Read_bcal_hadronic_eff2.py
src/plugins/monitoring/BCAL_Hadronic_Eff/ROOT_macros/plot_bcal_hadronic_eff.C
src/plugins/monitoring/BCAL_Hadronic_Eff/ROOT_macros/plot_bcal_hadronic_eff.py

Updated scripts to process the BCAL Hadronic Efficiencies. Does not change any analysis code. The plugin to generate the root trees is unchanged.

update scripts for BCAL_Hadronic_Eff and add README file

---

src/libraries/TAGGER/DTAGMGeometry.cc

This has been previously implemented for TAGH, I just copied the method over.

Only print TAGM energy correction once, not for every thread.

---

src/libraries/HDDM/DEventWriterHDDM.cc
src/libraries/HDDM/DEventWriterHDDM.h
src/plugins/Utilities/randomtrigger_skim/JEventProcessor_randomtrigger_skim.cc

1.  Write CCAL hits to the hddm 
2. Add a flag to disable checking beam fiducial for random trigger skims

Write CCAL to hddm. Add disable beam fiducials in random trigger skim

---

src/libraries/FCAL/DFCALCluster.cc
src/libraries/FCAL/DFCALCluster.h
src/libraries/FCAL/DFCALCluster_factory.cc
src/libraries/FCAL/DFCALGeometry.cc
src/libraries/FCAL/DFCALGeometry.h
src/libraries/FCAL/DFCALGeometry_factory.cc
src/libraries/FCAL/DFCALHit_factory.cc
src/libraries/FCAL/DFCALShower_factory.cc
src/libraries/FCAL/DFCALShower_factory.h
src/libraries/TRIGGER/DL1MCTrigger_factory.cc
src/plugins/Analysis/fcal_charged/DEventProcessor_fcal_charged.cc
src/plugins/Calibration/HLDetectorTiming/JEventProcessor_HLDetectorTiming.cc
src/plugins/monitoring/TRIG_online/JEventProcessor_TRIG_online.cc
src/programs/Analysis/hdview2/MyProcessor.cc
src/programs/Analysis/hdview2/hdv_mainframe.cc
src/programs/Analysis/hdview2/hdv_mainframe.h

These changes are designed to accommodate the planned insert to the FCAL while keeping the behavior for the current FCAL unchanged.   The code handling the insert is triggered by the presence of the lead tungstate blocks in the geometry XML.

Add insert to fcal

---

src/libraries/PID/DParticleID.cc

These were being printed out for every thread, also there was what I suppose is a debug printout left in.

Clean up dE/dx runtime messages

---

src/plugins/Analysis/F250_mode10_pedestal/JEventProcessor_F250_mode10_pedestal.cc
src/plugins/Analysis/F250_mode10_pedestal/JEventProcessor_F250_mode10_pedestal.h

Added new histograms (windowSigma) which give the collection of sigmas from each window for each channel.  These are Gaussian distributed.  The mean and error from theses histograms are what should be used for the noise in each channel.  Added a debug flag which shows some more calculation details for a single channel.

Peedestal noise plugin improvements

---

src/plugins/Calibration/TOF_calib/JEventProcessor_TOF_calib.cc
src/plugins/Calibration/TOF_calib/JEventProcessor_TOF_calib.h
src/plugins/Utilities/syncskim/JEventProcessor_syncskim.cc
src/plugins/include/HistogramTools.h
src/plugins/monitoring/BCAL_Eff/JEventProcessor_BCAL_Eff.cc
src/plugins/monitoring/TOF_TDC_shift/JEventProcessor_TOF_TDC_shift.cc

Mostly some bad lock and directory behavior.  Most of these were identified by David Lawrence.

Fix various ROOT bugs in plugins

---

src/libraries/ANALYSIS/DAnalysisResults_factory.cc
src/libraries/TRIGGER/DL1MCTrigger_factory.cc

This is likely a temporary solution for current trigger studies until we implement a better solution.
Prevents excess of error messages being printed to the screen.

Fix to look at trigger energy sums with EVIO data

---

src/programs/Utilities/SConscript
src/programs/Utilities/hd_rsai_gen/KO.config
src/programs/Utilities/hd_rsai_gen/Makefile
src/programs/Utilities/hd_rsai_gen/SConscript
src/programs/Utilities/hd_rsai_gen/hd_rsai_gen.cc
src/programs/Utilities/hd_rsai_gen/rs_macroutils.cc
src/programs/Utilities/hd_rsai_gen/rs_macroutils.h

Utility to help generate images for training Hydra models.

hd_rsai_gen

---

src/libraries/ANALYSIS/DAnalysisResults_factory.cc

basing the energy dependence on just the generated photon energy without worry about tagging is a smarter idea
added some other comments for future generations

minor changes to analysis level trigger monitoring 

---

src/libraries/HDGEOMETRY/DGeometry.cc
src/plugins/monitoring/SConscript
src/plugins/monitoring/lumi_mon/JEventProcessor_lumi_mon.cc
src/plugins/monitoring/lumi_mon/JEventProcessor_lumi_mon.h
src/plugins/monitoring/lumi_mon/SConscript
src/plugins/monitoring/scaler_primex/JEventProcessor_scaler_primex.cc
src/plugins/monitoring/scaler_primex/JEventProcessor_scaler_primex.h
src/plugins/monitoring/scaler_primex/SConscript

1. Add monitoring plugin to check tagger/ps calibration for lumi determination
2. Add plugin to create a root tree with fadc scalers, needed to monitor target density
3. Remove print out of the Be target in DGeometry

Primex recon

---

src/plugins/Utilities/SConscript
src/plugins/Utilities/dedx_tree/JEventProcessor_dedx_tree.cc
src/plugins/Utilities/dedx_tree/JEventProcessor_dedx_tree.h
src/plugins/Utilities/dedx_tree/SConscript

This is the plugin that I used to generate the trees for CDC dE/dx corrections (and also to draw a more finely-grained dE/dx histogram).

adding plugin dedx_tree, makes tree of CDC track angle, momentum, dEdx

---

src/plugins/Utilities/dedx_tree/scripts/README.md
src/plugins/Utilities/dedx_tree/scripts/checkmatrix.C
src/plugins/Utilities/dedx_tree/scripts/extendscalefactors.C
src/plugins/Utilities/dedx_tree/scripts/fitbinnedhistoslg.C
src/plugins/Utilities/dedx_tree/scripts/langaus.C
src/plugins/Utilities/dedx_tree/scripts/make_histo_into_text_file.C
src/plugins/Utilities/dedx_tree/scripts/makebinnedhistos.C
src/plugins/Utilities/dedx_tree/scripts/makescalefactors.C
src/plugins/Utilities/dedx_tree/scripts/makesimsinglebinnedhistos.C
src/plugins/Utilities/dedx_tree/scripts/plottingscripts/dots.C
src/plugins/Utilities/dedx_tree/scripts/plottingscripts/drawalldedxcuts.C
src/plugins/Utilities/dedx_tree/scripts/plottingscripts/drawdedxcuts.C
src/plugins/Utilities/dedx_tree/scripts/plottingscripts/drawdedxfromtchain.C
src/plugins/Utilities/dedx_tree/scripts/plottingscripts/drawsurf2.C
src/plugins/Utilities/dedx_tree/scripts/plottingscripts/make_histo_into_text_file.C
src/plugins/Utilities/dedx_tree/scripts/plottingscripts/plotdata.C
src/plugins/Utilities/dedx_tree/scripts/plottingscripts/plotf.C
src/plugins/Utilities/dedx_tree/scripts/plottingscripts/plotfdedx.C
src/plugins/Utilities/dedx_tree/scripts/smooth_histo.C

A bunch of helper C scripts, added to the dedx_tree plugin's subdirectory "scripts"

root C scripts for CDC dEdx corrections, see GlueX doc 4693

---

src/plugins/Calibration/TAGM_TW/tw_tagm.C

Add a simple script to fit TAGM TW, used for PrimEx

Add a simple script to fit TAGM TW, used for PrimEx

---

src/plugins/monitoring/lumi_mon/JEventProcessor_lumi_mon.cc

Add few histograms for calibration

Add few histograms for calibration

---

src/plugins/Analysis/compton/JEventProcessor_compton.cc
src/plugins/Utilities/ps_skim/JEventProcessor_ps_skim.cc
src/plugins/monitoring/lumi_mon/JEventProcessor_lumi_mon.cc

* fixed directory structure for compton and lumi_mon p[lugins
* removed front-panel triggers from PS skims

Aaust primex monitoring

---

src/libraries/ANALYSIS/DSourceComboTimeHandler.cc
src/libraries/ANALYSIS/DSourceComboer.cc
src/libraries/ANALYSIS/DSourceComboer.h
src/libraries/HDDM/DEventWriterREST.cc

write CCal clusters to REST by default and added few clarifying comments

Fix interference between ComCal clusters and analysis library

---

src/plugins/Utilities/SConscript
src/plugins/Utilities/cdc_emu/JEventProcessor_cdc_emu.cc
src/plugins/Utilities/cdc_emu/README.md
src/plugins/Utilities/cdc_scan/JEventProcessor_cdc_scan.cc
src/plugins/Utilities/cdc_scan/JEventProcessor_cdc_scan.h
src/plugins/Utilities/cdc_scan/README.md
src/plugins/Utilities/cdc_scan/SConscript

Low level CDC pulse data decoder

Nsj cdc scan

---

src/plugins/monitoring/lumi_mon/JEventProcessor_lumi_mon.cc

Add a few monitoring histograms

Add a few monitoring histograms

---

src/programs/Analysis/hd_root/hd_root.cc

Bitten by this too many times.

check that the input files are present and exit if none are found

---

src/plugins/monitoring/PSC_online/HistMacro_PSCTiming.C
src/plugins/monitoring/PS_online/HistMacro_PSTiming.C

some PS new monitoring macros

---

src/libraries/include/particleType.h

thanks to @furletov for discovering the mistake

updated DstarZero and DstarPlus masses according to PDG2020

---

src/libraries/HDDM/DEventWriterREST.cc

this time without pushing directly to the master...

Fix incorrect array usage for TAGGEDMCGEN photons in REST output

---

src/libraries/FMWPC/DFMWPCHit.h

Allows @zihlmann 's  FMWPC plug-in to compile.

Add namespace jana to header file.

---

src/plugins/monitoring/SConscript
src/plugins/monitoring/fa125_itrig/HistMacro_fa125_itrig.C
src/plugins/monitoring/fa125_itrig/JEventProcessor_fa125_itrig.cc
src/plugins/monitoring/fa125_itrig/JEventProcessor_fa125_itrig.h
src/plugins/monitoring/fa125_itrig/SConscript

This counts differences between the eventnumber and the fa125's itrigger. 
Good runs look like 
Bad runs look like 
or like 
@zihlmann  please could you take a look at the RSAI code in the Hist macro?

Nsj newplugin

---

src/plugins/Calibration/HLDetectorTiming/JEventProcessor_HLDetectorTiming.cc
src/plugins/Calibration/HLDetectorTiming/JEventProcessor_HLDetectorTiming.h

needed for upcoming run (algorithm from Drew Smith)
macros need to be restructured anyway, those will come later...

add TOF timing histograms for alignment without tracks

---

src/plugins/monitoring/fa125_itrig/HistMacro_fa125_itrig.C

Fixed some issues to get new HistMacro_fa125_itrig.C to play nicely with RootSpy and RSAI.

HistMacro_fa125_itrig.C bug fixes

---

src/plugins/Analysis/src-ct/1p1pi1pi0/DEventProcessor_1p1pi1pi0.cc
src/plugins/Analysis/src-ct/1p1pi1pi0/DEventProcessor_1p1pi1pi0.h
src/plugins/Analysis/src-ct/1p2pi/DEventProcessor_1p2pi.cc
src/plugins/Analysis/src-ct/1p2pi/DEventProcessor_1p2pi.h

Fixed memory leak in both SRC/CT plugins + cosmetics

Aaust src plugin fix

---

src/libraries/FMWPC/DCTOFPoint_factory.cc

Include an include of cmath.

---

src/libraries/FCAL/DFCALCluster_factory_Island.cc
src/libraries/FCAL/DFCALGeometry.cc
src/libraries/FCAL/DFCALGeometry.h

Fixes issue with clusterization (using the island algorithm) at the border between the lead glass and the insert for the FCAL2 geometry.

Fcal island border fix

---

src/libraries/TRACKING/DTrackCandidate_factory_StraightLine.cc
src/libraries/TRACKING/DTrackFinder.cc
src/libraries/TRACKING/DTrackFinder.h
src/libraries/TRACKING/DTrackFitterStraightTrack.cc

Improves track finding for cosmics in the CDC.

Straight track update jan22

---

src/plugins/monitoring/FMWPC_online/FMWPC_hits.C
src/plugins/monitoring/FMWPC_online/JEventProcessor_FMWPC_online.cc

* Added histograms for calibrated hits, which can also be used for simulated data
* Macro to plot calibrated hits for all 6 planes
* Release root lock at the end

Added histograms for calibrated hits

---

src/SBMS/sbms.py
src/libraries/FMWPC/DFMWPCCluster.h
src/libraries/FMWPC/DFMWPCCluster_factory.cc
src/libraries/FMWPC/DFMWPCMatchedTrack_factory.cc
src/plugins/Analysis/CPPMVAtree/JEventProcessor_CPPMVAtree.cc
src/programs/Analysis/hdview2/MyProcessor.cc
src/programs/Analysis/hdview2/MyProcessor.h
src/programs/Analysis/hdview2/fmwpc_mainframe.cc
src/programs/Analysis/hdview2/fmwpc_mainframe.h
src/programs/Analysis/hdview2/hdv_debugerframe.h
src/programs/Analysis/hdview2/hdv_endviewAframe.h
src/programs/Analysis/hdview2/hdv_endviewBframe.h
src/programs/Analysis/hdview2/hdv_fulllistframe.h
src/programs/Analysis/hdview2/hdv_mainframe.cc
src/programs/Analysis/hdview2/hdv_mainframe.h
src/programs/Analysis/hdview2/hdv_optionsframe.h
src/programs/Analysis/hdview2/trk_mainframe.cc

This mostly involves adding the FMWPC inspector to hdview2. One significant change that includes is modifying the automatic ROOT dictionary generation SBMS does for any header files including the string "ClassDef". Up until now, rootcling was run on each of these to generate individual dictionary .cc files. This is actually not the best way to do this. The change here runs rootcling just once in a directory but gives all (appropriate) header files in order to create a single .cc file containing all dictionaries. The dictionary generation feature is used by most monitoring plugins as well as hdview2.
This also includes changes to DFMWPCCluster to add in the first_wire and last_wire fields. A couple of other relatively minor changes to CPP-specific parts of the code are also included.
This …

CPP FMWPC to hdview2 and SBMS + root dictionary

---

src/plugins/Calibration/PS_timing/HistMacro_PSTiming.C

this is useful for monitoring internal PS timing calibrations

add new monitoring plot for PS_timing plugin

---

src/libraries/FMWPC/DFMWPCCluster.h
src/libraries/FMWPC/DFMWPCCluster_factory.cc
src/libraries/FMWPC/DFMWPCCluster_factory.h
src/libraries/HDGEOMETRY/DGeometry.cc
src/libraries/HDGEOMETRY/DGeometry.h
src/plugins/monitoring/FMWPC_online/JEventProcessor_FMWPC_online.cc

translate FMWPC clusters to global coordinates based on HDDS geometry

Aaust fmwpc reco

---

src/libraries/HDDM/DEventSourceHDDM.cc
src/libraries/HDDM/event.xml

Add q to fmwpc hit and truthhit xml entries in a backward-compatible manner

Fmwpc hddm fix

---

src/libraries/FCAL/DFCALCluster_factory_Island.cc

Updates to try to improve close cluster separation

Fcal island update feb22

---

src/libraries/ANALYSIS/DHistogramActions_Independent.cc
src/libraries/ANALYSIS/DHistogramActions_Independent.h
src/plugins/Analysis/monitoring_hists/HistMacro_NumLowLevelObjects_p1.C
src/plugins/Analysis/monitoring_hists/HistMacro_NumLowLevelObjects_p2.C
src/plugins/monitoring/FMWPC_Performance/FMWPC_Performance.C
src/plugins/monitoring/FMWPC_Performance/JEventProcessor_FMWPC_Performance.cc
src/plugins/monitoring/FMWPC_Performance/JEventProcessor_FMWPC_Performance.h
src/plugins/monitoring/FMWPC_Performance/SConscript
src/plugins/monitoring/SConscript

new plugin for FMWPC performance, added FMWPCHits to monitoring_hists

Aaust fmwpc performance

---

src/libraries/DAQ/JEventSource_EVIOpp.cc
src/libraries/DAQ/JEventSource_EVIOpp.h

As suggested by @faustus123 - this should resolve issue #643

handle fADC125 emulation on pure raw data based on the TTab

---

src/plugins/Calibration/HLDetectorTiming/JEventProcessor_HLDetectorTiming.cc

Adding these plots before I forget.
Note to @sdobbs - Please deprecate HistogramTools.h before the run

Some plots for FMPWC timing calibration

---

src/plugins/monitoring/FMWPC_online/CTOF_occupancy.C
src/plugins/monitoring/FMWPC_online/JEventProcessor_FMWPC_online.cc

CTOF occupancy monitoring

---

src/plugins/monitoring/FMWPC_online/CTOF_occupancy.C
src/plugins/monitoring/FMWPC_online/FMWPC_occupancy.C
src/plugins/monitoring/FMWPC_online/JEventProcessor_FMWPC_online.cc

correct normalization for occupancies, input Nevents for hydra

Aaust fmwpc hydra fix

---

src/libraries/TAGGER/DTAGHHit_factory_Calib.cc
src/libraries/TAGGER/DTAGMHit_factory_Calib.cc

are marged dead in the channel quality in ccdb [rtj]

* reject tagger microscope and hodoscope hits from counters that

---

src/plugins/monitoring/highlevel_online/HistMacro_LEDTrigger_CPP.C
src/plugins/monitoring/highlevel_online/HistMacro_Trigger_CPP.C

replaces DIRC LED with CTOF FP trigger (bit 6)

new trigger monitoring macros for CPP/NPP run

---

src/libraries/FMWPC/DCPPEpEm.h
src/libraries/FMWPC/DCPPEpEm_factory.cc
src/plugins/monitoring/FMWPC_Performance/JEventProcessor_FMWPC_Performance.cc

Also add/uncomment  related histograms to FMWPC_Performance

Add epi classifier to DCPPEpEm factory

---

src/plugins/Calibration/PSC_TW/JEventProcessor_PSC_TW.cc
src/plugins/monitoring/CDC_dedx/CDC_dedx.C

it does not return to the main directory in the end

The PSC_TW plugin changes the file structure

---

src/plugins/Calibration/HLDetectorTiming/HistMacro_OnlineCalorimeter.C
src/plugins/Calibration/HLDetectorTiming/HistMacro_OnlinePID.C
src/plugins/Calibration/HLDetectorTiming/HistMacro_OnlinePID_CPP.C
src/plugins/Calibration/HLDetectorTiming/HistMacro_OnlineRF_CPP.C
src/plugins/Calibration/HLDetectorTiming/HistMacro_OnlineTagger.C
src/plugins/Calibration/HLDetectorTiming/HistMacro_OnlineTracking.C

initial monitoring changes for CPP

Sdobbs jun2022 mon update

---

src/plugins/Calibration/HLDetectorTiming/HistMacro_OnlineCalorimeter.C
src/plugins/Calibration/HLDetectorTiming/HistMacro_OnlinePID_CPP.C
src/plugins/Calibration/HLDetectorTiming/HistMacro_OnlineTagger.C
src/plugins/Calibration/HLDetectorTiming/HistMacro_OnlineTracking.C

updated set points for current CPP production running

---

src/libraries/TRACKING/DTrackFitterKalmanSIMD.cc
src/libraries/include/DMatrix3x3.h
src/libraries/include/DMatrix4x4.h
src/libraries/include/DMatrix5x5.h

Fixes bugs in code that checks that the covariance matrix in the kalman filter code is positive definite and reduces the number of times the check is performed.  Removes dependence on root TMatrix classes in this check.

Fix check pos def

---

src/plugins/monitoring/SConscript
src/plugins/monitoring/primex-online/Combination.cc
src/plugins/monitoring/primex-online/Combination.h
src/plugins/monitoring/primex-online/JEventProcessor_myanalyzer.cc
src/plugins/monitoring/primex-online/JEventProcessor_myanalyzer.h
src/plugins/monitoring/primex-online/Nice1D.C
src/plugins/monitoring/primex-online/Nice1Db.C
src/plugins/monitoring/primex-online/Nice3D2D.C
src/plugins/monitoring/primex-online/Nicer1D.C
src/plugins/monitoring/primex-online/SConscript
src/plugins/monitoring/primex-online/primex_elasticity.C
src/plugins/monitoring/primex-online/primex_invmasses.C
src/plugins/monitoring/primex-online/primex_millecious.C

PrimEx-eta online monitoring:
1/ Plot for basic selection criteria 3 eta decays invariant mass: gg, pi0pi0pi0, and pi9pippim
2/ Elasticity & polar angles
3/ Some millecious plots (TOF veto, time, FCAL energy sum)

Add primex online monitoring

---

src/plugins/Utilities/eta2g_primexd_skim/JEventProcessor_eta2g_primexd_skim.cc
src/plugins/Utilities/eta6g_primexd_skim/JEventProcessor_eta6g_skim.cc

Modified primex eta > 2g & 3pi0 skims

Ijaegle primex skims

---

src/plugins/Calibration/HLDetectorTiming/HistMacro_OnlineCalorimeter.C
src/plugins/Calibration/HLDetectorTiming/HistMacro_OnlinePID.C
src/plugins/Calibration/HLDetectorTiming/HistMacro_OnlineTagger.C
src/plugins/Calibration/HLDetectorTiming/HistMacro_OnlineTracking.C

update timing setpoints for 2023

---

src/plugins/Calibration/HLDetectorTiming/JEventProcessor_HLDetectorTiming.cc

Fix typo that stopped BCAL TDC hit times from being filled

---

src/plugins/Calibration/HLDetectorTiming/JEventProcessor_HLDetectorTiming.cc
src/plugins/Calibration/HLDetectorTiming/JEventProcessor_HLDetectorTiming.h

Add a histogram to calibrate CDC times for when the SC isn't installed

---

src/libraries/HDDM/DEventSourceHDDM.cc

This is intended to fix issue #722.

Detect and fix inconsistent particle types in thrown MC data.

---

src/libraries/ANALYSIS/DHistogramActions_Independent.cc
src/libraries/ANALYSIS/DHistogramActions_Independent.h
src/plugins/Analysis/monitoring_hists/DEventProcessor_monitoring_hists.cc
src/plugins/Analysis/monitoring_hists/DEventProcessor_monitoring_hists.h
src/plugins/Calibration/BCAL_TDC_Timing/JEventProcessor_BCAL_TDC_Timing.cc
src/plugins/Calibration/BCAL_TDC_Timing/JEventProcessor_BCAL_TDC_Timing.h

- add flags to get BCAL matching histograms
- add flags to get BCAL timing calibration histograms

monitoring updates for CPP run

---

src/libraries/TRIGGER/DL1MCTrigger_factory.cc
src/libraries/TRIGGER/DL1MCTrigger_factory.h

Initial implementation of the calorimeter & ST trigger

L1 trigger

---

src/libraries/TOF/DTOFHit_factory.h
src/libraries/TOF/DTOFPoint_factory.cc

Fixes a couple of bugs flagged by valgrind.

Tof point bug fix

---

src/SBMS/SConstruct.plugin
src/programs/Utilities/analysis/MakeReactionPlugin.pl

prepare mkplugin and MakeReactionPlugin for rhel8

---

src/libraries/FMWPC/DFMWPCHit_factory.cc
src/plugins/Calibration/FCAL_Pi0TOF/JEventProcessor_FCAL_Pi0TOF.cc
src/plugins/Utilities/eta6g_primexd_skim/JEventProcessor_eta6g_skim.cc

Fix a few compilation warnings: unused variables and signed int comparisons

Suppress compiler warnings

---

src/libraries/FCAL/DFCALCluster_factory_Island.cc
src/libraries/FCAL/DFCALCluster_factory_Island.h
src/libraries/FCAL/DFCALGeometry.cc
src/libraries/FCAL/DFCALShower_factory.cc
src/libraries/FCAL/DFCALShower_factory.h

Various updates to the island algorithm implementation:
-- Added R-dependence for shower shape parameter b
-- Added S-curve correction
-- Added way to toggle merging of hits on either side of the insert boundary

Ia update sep23

---

src/plugins/Alignment/tools/README.md
src/plugins/Alignment/tools/input_example
src/plugins/Alignment/tools/pede.py

Also, README.md and input_example files are added in the same directory.

Update plugins/Alignment/tools/pede.py to make it more user-friendly

---

src/libraries/HDGEOMETRY/DGeometry.cc
src/libraries/HDGEOMETRY/DGeometry.h
src/libraries/TOF/DTOFPaddleHit_factory.cc
src/libraries/TOF/DTOFPaddleHit_factory.h
src/libraries/TOF/DTOFPoint_factory.cc
src/libraries/TOF/DTOFPoint_factory.h

Addresses thread safety issue that lead to crashes when files with multiple run numbers were analyzed using many processing threads.

Tof geom fix oct23

---

src/plugins/Calibration/HLDetectorTiming/HistMacro_TrackingTiming_CPP.C

needed for upcoming data quality monitoring

Add new tracking timing monitoring plot for CPP

---

src/plugins/monitoring/FMWPC_online/CTOF_energy.C
src/plugins/monitoring/FMWPC_online/CTOF_occupancy.C
src/plugins/monitoring/FMWPC_online/FMWPC_energy.C
src/plugins/monitoring/FMWPC_online/FMWPC_occupancy.C
src/plugins/monitoring/FMWPC_online/JEventProcessor_FMWPC_online.cc

Added monitoring plots in FMWPC_online plugin for CTOF and MWPC. Added 2 new root macros for RootSpy for CTOF and FMWPCs timing and energy

added energy and timing plots

---

src/SBMS/sbms_setenv.py

Fix SBMS TabError: inconsistent use of tabs and spaces in indentation

---

src/libraries/FMWPC/DFMWPCHit.h
src/libraries/FMWPC/DFMWPCHit_factory.cc
src/libraries/FMWPC/DFMWPCHit_factory.h
src/libraries/HDDM/DEventSourceREST.cc
src/libraries/HDDM/DEventSourceREST.h
src/libraries/HDDM/DEventWriterREST.cc
src/libraries/HDDM/DEventWriterREST.h
src/libraries/HDDM/rest.xml

* write FMWPC hits to REST file
* remove quality cuts
* get threshold and timing cut from CCDB or commandline

Aaust fmwpc reco2

---

src/libraries/FCAL/DFCALShower_factory.cc

I found a bug has for consquence to never use the version 3. I just changed a false to a true

Ijaegle nonlinear

---

src/libraries/FCAL/DFCALShower_factory.cc
src/libraries/FCAL/DFCALShower_factory.h

1/ Ilya's code for the non-linear correction has been copy-paste
2/ 2 tables are added to ccdb
A new monitoring plugins will be also added later in the review process

Add CPP non-linear correction

---

src/libraries/TRIGGER/DL1MCTrigger_factory.cc

Fix trigger bit for the BCAL trigger

Fix BCAL trigger bit

---

src/libraries/FMWPC/DCTOFHit_factory.cc
src/libraries/HDDM/DEventSourceHDDM.cc
src/libraries/HDDM/DEventWriterHDDM.cc
src/libraries/HDDM/DEventWriterHDDM.h

Added FMWPC and CTOF objects to HDDM Event Writer

fwmpc and ctof added to hddm

---

src/libraries/BCAL/DBCALHit_factory.cc
src/libraries/BCAL/DBCALHit_factory.h

Add new table to mask bad channels for BCAL

Add bad channel mask for BCAL

---

src/plugins/Calibration/BCAL_attenlength_gainratio/JEventProcessor_BCAL_attenlength_gainratio.cc

removed warning from leftover variables

---

src/plugins/monitoring/FCAL_cpp/HistMacro_FCAL_cpp.C
src/plugins/monitoring/FCAL_cpp/JEventProcessor_FCAL_cpp.cc
src/plugins/monitoring/FCAL_cpp/JEventProcessor_FCAL_cpp.h

FCAL row columns were swapped - corrected, and made out of trigger channels finding more straightforward, log scale for this histogram was removed

modified out of trigger FCAL channels finding, and swapped row<->col

---

src/plugins/Alignment/FDC_t0_alignment/mille.py
src/plugins/Alignment/FDC_t0_alignment/swif2.py
src/plugins/Alignment/FDC_t0_alignment/update_official_ccdb.py

minor changes to t0 calibration scripts

---

src/libraries/TOF/DTOFHit_factory.cc
src/libraries/TOF/DTOFHit_factory.h

Now handle both bad ADC and TDC channels

Update TOF bad channel handling

---

src/plugins/monitoring/TrackingPulls/JEventProcessor_TrackingPulls.cc

Add ROOT locks to TrackingPulls

---

src/libraries/TRIGGER/DL1MCTrigger_factory_DATA.cc
src/libraries/TRIGGER/DL1MCTrigger_factory_DATA.h
src/libraries/TRIGGER/DTrigger_factory.cc
src/libraries/TRIGGER/TRIGGER_init.cc

Initial try at simulating the trigger energy sums for data, mainly for use for comparing to simulation.
Don't take these values too seriously!  But it's better than what was previously implemented.
The code works and should probably sit somewhere that's not just in one of my private branches...

First try at simulating trigger energy sums for data

---

src/libraries/DAQ/DBeamCurrent_factory.cc

For future monitoring / debugging purposes

Modify status message to help with future monitoring of beam fiducial tables

---

src/libraries/DAQ/DParsedEvent.h
src/plugins/Analysis/monitoring_hists/DEventProcessor_monitoring_hists.cc
src/plugins/Analysis/monitoring_hists/DEventProcessor_monitoring_hists.h
src/programs/Analysis/hd_dump/hd_dump.cc
src/programs/Analysis/hd_root/MyProcessor.cc
src/programs/Analysis/hd_root/hd_root.cc

- Re-enable JApplication destruction
- Fix monitoring_hists/IsEvent histogram

More fixes

---

src/plugins/monitoring/highlevel_online/HistMacro_NumHighLevelObjects.C
src/plugins/monitoring/highlevel_online/JEventProcessor_highlevel_online.cc

remove high level objects plot from macro, make TDC-ADC time plot 2 panels
updating monitoring for upcoming run
first PR of 2025!

update high-level monitoring plot

---

src/libraries/ANALYSIS/DHistogramActions_Independent.cc

Fixes bugs that caused an exception when running the monitoring_hists plugin on rest files.

Extrapolation bug fix jan25

---

src/plugins/monitoring/occupancy_online/JEventProcessor_occupancy_online.cc

bin counting starts with 1

---

src/plugins/monitoring/occupancy_online/ECAL_occupancy.C
src/plugins/monitoring/occupancy_online/JEventProcessor_occupancy_online.cc
src/plugins/monitoring/occupancy_online/JEventProcessor_occupancy_online.h

Ecal occupancy

---

src/libraries/BCAL/DBCALHit_factory.cc
src/libraries/BCAL/DBCALShower_factory_IU.cc
src/libraries/DAQ/HDEVIO.h
src/libraries/TRACKING/DTrackCandidate_factory_FDC.cc
src/libraries/TRACKING/DTrackCandidate_factory_FDCpseudo.cc
src/libraries/TRACKING/DTrackFitter.h
src/libraries/TTAB/DTTabUtilities.cc
src/plugins/Utilities/evio_writer/HDEVIOWriter.cc
src/plugins/monitoring/TrackingPulls/JEventProcessor_TrackingPulls.cc

slowly getting rid of them all...

Minor changes to get rid of some compiler warnings

---

src/plugins/Utilities/evio_writer/HDEVIOWriter.cc

Let's see if this helps figure out where the rare header corruption is happening

Fix some sanity checks to the EVIO output code

---

src/plugins/monitoring/BEAM_online/JEventProcessor_BEAM_online.cc

Fix locking in BEAM_online plugin

---

src/libraries/HDDM/DEventWriterHDDM.cc

Looks like it slipped in at the JANA2 port

Remove repeated lines in HDDM writer

---

src/plugins/monitoring/fa125_itrig/JEventProcessor_fa125_itrig.cc
src/plugins/monitoring/highlevel_online/HistMacro_Kinematics.C
src/plugins/monitoring/highlevel_online/JEventProcessor_highlevel_online.cc
src/plugins/monitoring/highlevel_online/JEventProcessor_highlevel_online.h

Update kinematic panel to simplify and be more useful
If we want to add more info, we could add the p vs. beta plots for more detectors

Update online high level monitoring plugin

---

src/plugins/Analysis/TPOL_tree/JEventProcessor_TPOL_tree.cc
src/plugins/monitoring/CDC_Efficiency/JEventProcessor_CDC_Efficiency.cc
src/plugins/monitoring/FCAL_online/JEventProcessor_FCAL_online.cc
src/plugins/monitoring/RF_online/JEventProcessor_RF_online.cc
src/plugins/monitoring/TAGM_online/JEventProcessor_TAGM_online.cc

Contributions from @aaust and me.
Checked that REST production plugins ran over a small sample of events.

Fix some lingering locking problems

---

src/libraries/TRD/DTRDHit_factory_Calib.cc
src/libraries/TRD/DTRDStripCluster_factory.cc
src/libraries/TRD/DTRDStripCluster_factory_RAW.cc

clean up warnings in TRD library

---

src/libraries/ANALYSIS/DEventWriterROOT.cc
src/libraries/DAQ/DAQ_init.cc
src/libraries/DAQ/DBeamHelicity_factory_CORRECTED.cc

also load a tagged factory, which got accidentally left out of the previous PR
This resolves #919

Fix wrong use of GetSingle() that was causing crashes in DEventWriterROOT

---

src/libraries/ECAL/DECALCluster.h
src/libraries/ECAL/DECALCluster_factory.cc
src/libraries/ECAL/DECALCluster_factory.h
src/libraries/ECAL/DECALGeometry.cc
src/libraries/ECAL/DECALGeometry.h
src/libraries/ECAL/DECALShower_factory.cc
src/libraries/FCAL/DFCALCluster.h
src/libraries/PID/DNeutralShower_factory.cc
src/libraries/PID/DNeutralShower_factory.h
src/libraries/include/GlueX.h

Add channel number for ECAL hit with the highest energy, needed for pi0/Compton calibrations.  Add hits as associated objects to ECAL clusters.  Add preliminary code to stitch showers together in the ECAL/FCAL transition region.  Flag these DNeutralShowers 
with SYS_ECAL_FCAL detector system type.

Fcal2 update apr2025

---

src/libraries/TRD/DTRDHit_factory_Calib.cc
src/plugins/monitoring/TRD_online/TRD_hit_2025.C

Small changes - add new plots to ROOTSPY macro that are better suited for Kr gas monitoring, plus small tweak to limiting the time window to avoid firmware timestamp

update ROOTSPY plots... again

---

src/SBMS/sbms.py
src/programs/Analysis/hd_root/hd_root.cc

Cherry-picked the two remaining commit's from David's branch [4.52.1+jana2c++20](https://github.com/JeffersonLab/halld_recon/tree/4.52.1_jana2c%2B%2B20), which is running in the counting house. When this is in the master, it will make it much easier to keep the counting house up to date.

Master c++20 cherry

---

src/libraries/TRD/DTRDHit_factory.cc
src/libraries/TRD/DTRDHit_factory_Calib.cc
src/libraries/TRD/DTRDHit_factory_Calib.h
src/libraries/TRD/DTRDPoint_factory.cc
src/libraries/TRD/DTRDPoint_factory_Hit.cc
src/libraries/TRD/DTRDPoint_factory_Hit.h
src/plugins/monitoring/TRD_online/JEventProcessor_TRD_online.cc
src/plugins/monitoring/TRD_online/TRD_hit_2025.C

Set parameter defaults more sensibly, add a few new histograms and tweak the ranges of existing ones, remove old comments, set Z value in Point_Hit objects to be calculated consistent with the default Point objects

Tweaked histograms, new Z projection histos, set better defaults

---

src/plugins/monitoring/FDC_Efficiency/JEventProcessor_FDC_Efficiency.cc

something must have gone wrong in one of the many rebases during the jana2 transition

fix some FDC efficiency histograms

---

src/libraries/ANALYSIS/DHistogramActions_Independent.cc
src/libraries/ANALYSIS/DHistogramActions_Reaction.cc
src/libraries/ANALYSIS/DHistogramActions_Reaction.h
src/libraries/ANALYSIS/DSourceComboP4Handler.cc
src/libraries/ANALYSIS/DSourceComboTimeHandler.cc
src/libraries/ANALYSIS/DSourceComboer.cc
src/libraries/ANALYSIS/DSourceComboer.h

Initial implementation of ECAL showers into the ANALYSIS library.  Note that the default PID selections should be updated.
Also some updates to the track/ECAL matching plots.

Updates for ECAL analysis

---

src/plugins/Analysis/p3pi_hists/DCustomAction_p3pi_Pi0Cuts.cc
src/plugins/Analysis/p3pi_hists/DCustomAction_p3pi_Pi0Cuts.h
src/plugins/Analysis/p3pi_hists/DCustomAction_p3pi_Pi0Cuts_FCAL2.cc
src/plugins/Analysis/p3pi_hists/DCustomAction_p3pi_Pi0Cuts_FCAL2.h
src/plugins/Analysis/p3pi_hists/DReaction_factory_p3pi_hists.cc
src/plugins/Analysis/p3pi_hists/HistMacro_p3pi.C

- Add reactions and histograms for different combinations of calorimeters 
- update the macro so that it's more consistent with previous runs

 Update p3pi_hists for FCAL2

---

src/plugins/Analysis/p2pi_hists/HistMacro_CircMonitor.C

Rebin if number of total entries in all histograms is less than 40k
Change default fit function to 
[0]+ ([1]*sin(2*x[0]))/(1 + 0.5*[2]*cos(2*x[0])+[3]*cos(x[0]))
If less than 10k events switch fit function to 
[0]+ ([1]*sin(2*x[0]))
Type of fit function used is displayed on canvas with parameter.

change circular monitor fit function, and add rebin switch

---

src/plugins/monitoring/highlevel_online/HistMacro_HelicityMon.C

Currently plots helicity asymmetry of the trigger bits.

Add macro for monitoring the helicity.

---

src/libraries/DAQ/DBeamHelicity_factory.cc

Addition for testing helicity decoder board

---

src/plugins/Calibration/SConscript
src/plugins/Calibration/cal_cal/JEventProcessor_cal_cal.cc
src/plugins/Calibration/cal_cal/JEventProcessor_cal_cal.h
src/plugins/Calibration/cal_cal/SConscript
src/plugins/Calibration/cal_cal/SConstruct
src/plugins/Utilities/evio_writer/DEVIOBufferWriter.cc
src/plugins/Utilities/pi0fcaltofskim/JEventProcessor_pi0fcaltofskim.cc

1. Add ECAL into the fcal pi0 skimmer but the TOFPoint is missing
2. Add my calorimeter calibration plugin that does energy, energy dependence correction, and timing calibration.

Ig cal cal

---

src/programs/Analysis/hdview2/EventViewer.cc
src/programs/Analysis/hdview2/hdv_mainframe.cc
src/programs/Analysis/hdview2/hdv_mainframe.h

Draws ECAL and colors hit ECAL blocks when present.   Displays green circles for reconstructed showers in ECAL region.  Displays side view of insert when present.

Add ecal to hdview2

---

src/plugins/Analysis/SConscript
src/plugins/Analysis/led_monitor/JEventProcessor_led_monitor.cc
src/plugins/Analysis/led_monitor/JEventProcessor_led_monitor.h
src/plugins/Analysis/led_monitor/RootHeader.h
src/plugins/Analysis/led_monitor/SConstruct
src/plugins/Analysis/led_monitor/fit.C
src/plugins/Analysis/led_monitor/plot_led.C

Add pligin to monitor ECAL LED

Add pligin to monitor ECAL LED

---

src/plugins/Analysis/SConscript
src/plugins/Analysis/ecal_waveforms/JEventProcessor_ecal_waveforms.cc
src/plugins/Analysis/ecal_waveforms/JEventProcessor_ecal_waveforms.h
src/plugins/Analysis/ecal_waveforms/README
src/plugins/Analysis/ecal_waveforms/RootHeader.h
src/plugins/Analysis/ecal_waveforms/SConstruct

Add a plugin to plot signal waveforms for reference PMTs and ECAL modules using data collected with the flash 
ADC in raw mode (Mode 10).

Add a plugin to plot signal waveforms for reference PMTs and ECAL

---

src/libraries/DAQ/DBeamHelicity_factory.cc
src/libraries/DAQ/DBeamHelicity_factory.h
src/plugins/Calibration/HLDetectorTiming/JEventProcessor_HLDetectorTiming.cc

accidentally required ECAL to exist, breaking backwards compatibility

Fix HLDetectorTiming to work with pre-FCAL2 data

---

src/dana_rest.hddm
src/libraries/ANALYSIS/DHistogramActions_Reaction.cc
src/libraries/PID/DChargedTrackHypothesis.h

* t1/beta was not calculated for ECAL
* we always used the start counter covarance matrix for the fcal
* some ECAL histograms had the wrong titles

Fix few bugs in the analysis library 

---

src/plugins/monitoring/highlevel_online/HistMacro_Vertex.C
src/plugins/monitoring/highlevel_online/JEventProcessor_highlevel_online.cc
src/plugins/monitoring/highlevel_online/JEventProcessor_highlevel_online.h

Changes to the highlevel_online plugin and Vertex plotting macro to improve online monitoring of vertices in target.

Changes to improve online monitoring of vertices in target.

---

src/plugins/Utilities/trigger_skims/JEventProcessor_trigger_skims.cc

Feedback from Sasha, I was counting starting from 1 rather than 0

Update ECAL trigger skims
